CityOfBoston/boston.gov-d8

config/default/core.entity_view_display.taxonomy_term.features.contact.yml
config/default/core.entity_view_display.taxonomy_term.features.default.yml
config/default/core.entity_view_display.taxonomy_term.features.department_listing.yml
config/default/core.entity_view_display.taxonomy_term.features.published_by.yml
config/default/core.extension.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_form_display.taxonomy_term.features.default.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_view_display.taxonomy_term.features.contact.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_view_display.taxonomy_term.features.default.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_view_display.taxonomy_term.features.department_listing.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_view_display.taxonomy_term.features.popup_icon.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/core.entity_view_display.taxonomy_term.features.published_by.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/field.field.taxonomy_term.features.field_icon.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/language.content_settings.taxonomy_term.features.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/config/install/taxonomy.vocabulary.features.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/vocab_features.info.yml
docroot/modules/custom/bos_vocab/modules/vocab_features/vocab_features.install

Creates module that provides `features` vocabulary.
I've noted this in our spreadsheet, but this migration relies on the image asset migration. Once that's in place this migration should work.

Create vocab_features module

---

.lando.yml
scripts/phing/files/xdebug.ini
scripts/phing/tasks/setup.xml

@davidrkupton These updates allow drush + xdebug to work in VSCode. Turns out it had nothing to do with the IDEKey :man_shrugging:. 
The [lando docs](https://docs.devwithlando.io/tutorials/drupal8.html#recipe) say that I should have been able to do something like `drush: path:/app/vendor/bin/drush` , but for some reason that wasn't working for me. This does essentially the same thing.

Update lando xdebug config to connect on drush commands

---

docroot/modules/custom/bos_core/src/Commands/BosCoreCommands.php
docroot/modules/custom/bos_core/src/componentizer_templates/componentizer_template.info.yml
docroot/modules/custom/bos_core/src/componentizer_templates/componentizer_template.install
docroot/modules/custom/bos_core/src/componentizer_templates/componentizer_template.module

Adds a drush command to automate the initial creation of a component module. You can use it like this:
`lando drush componetize bos_photo --components=photo`
This will create a module called `bos_photo` as a submodule of `bos_components` and copy over the relevant configuration items. If you want multiple components to be housed in a single module, pass a comma separated list of machine names into `--components`
This command is far from perfect, and it's output should be reviewed by a human before committing, but it should save some of the repetitive manual work we're doing to create these component modules.

Add drush command to create component modules

---

.travis.yml
docroot/themes/custom/bos_theme/bos_theme.theme

This "fixes" the situation where the attributes element of the $variables array is an array and not a Drupal\core\Template\Attribute object.
Drupal generally handles both situations provided there is consistency, but the attributes array is more correct (see "What behavior were you expecting?" on this link https://www.drupal.org/project/drupal/issues/3015783.)
When created as an Attribute object its allows adding elements (e.g. classes) in both styles:
`$variables["attributes"]["class"][] = "my-class";` (D7 syntax), and
`$variables["attributes"]->addClass("my-class");` (D8 OOPHP approach)
The problem is that when the attributes element is created as an array, any later attempted use (e.g. an element insertion) as if it were an object throws a PHP Error to the logs, and the insertion is …

Attributes

---

docroot/modules/custom/bos_components/templates/field--component--field-component-title.html.twig
docroot/themes/custom/bos_theme/bos_theme.theme
docroot/themes/custom/bos_theme/js/component-navigation.boston.js

(Majority of `bos_theme.theme` mods are from a merge i did locally and are a duplicate of whats in the `housekeeping` PR - so there should only minor changes in bos_theme.theme in `develop` if I merge this after `houskeeping`)
But, I would like to say ...   
The js is OK and the functionality is correct across the 980px breakpoint, animations are smooth and the menu collapses much more nicely than in D7 - but the problem is that lines 58-120 use jQuery and lines 120+ use js directly on the DOM.  My gut says we should have a single approach used in a single script ... but not sure if its worth the effort.  I also recall that mixing up like this can cause memory errors if jQuery and DOM objects are exchanged, but I don't think we will have that situation here. 
.. thoughts ?

In page menu

---

docroot/modules/custom/bos_components/modules/bos_quote/templates/paragraph--quote.html.twig
docroot/modules/custom/bos_core/bos_core.module
docroot/modules/custom/bos_migration/src/Plugin/migrate/process/RichTextToMediaEmbed.php

D7 media embeds are a weird hybrid of a token + json. Needless to say, I forgot about them in my original migration.
This PR translates those values to the D8 `entity_embed` style.
Drupal 7 supports inline styles on entity embeds, so those will now be supported on `entity_embeds` in D8. However, this is sort of secret because there is no ui to configure them. Instead, you can add inline style to an `entity_embed` using `data-style="display: block;"`. We likely don't want content editors using inline styles anyways, so this should be ok.

Update media migration

---

docroot/modules/custom/bos_core/bos_core.module

For paragraphs: 
This will now install the icon into a subfolder under the public files folder, then register the file as a file entity, then associate that file entity (via it'ss uuid) with the paragraph_type being installed.
**Note:**
_To work:_
1. Icons must be in the root folder of the module being installed.
2. Icons must be named entity_icon.svg, where the entity = the name of the paragraph being installed.

Fix icon installer

---

config/default/core.entity_form_display.node.event.default.yml
config/default/core.entity_form_display.node.site_alert.default.yml
config/default/core.entity_view_display.node.event.default.yml
config/default/core.entity_view_display.node.site_alert.default.yml
config/default/field.field.node.event.field_date_range.yml
config/default/field.field.node.event.field_intro_image.yml
config/default/field.field.node.site_alert.field_date_range.yml
config/default/field.field.node.site_alert.field_extra_info.yml
config/default/field.field.node.site_alert.field_icon.yml
config/default/field.field.node.site_alert.field_link.yml
config/default/field.field.node.site_alert.field_theme.yml
config/default/field.field.node.site_alert.title_field.yml
config/default/views.view.site_alerts.yml
docroot/modules/custom/bos_components/modules/bos_commissions/bos_commissions.libraries.yml
docroot/modules/custom/bos_components/modules/bos_lightbox/bos_lightbox.libraries.yml
docroot/modules/custom/bos_components/modules/bos_map/bos_map.libraries.yml
docroot/modules/custom/bos_content/modules/node_event/node_event.info.yml
docroot/modules/custom/bos_content/modules/node_event/node_event.module
docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.info.yml
docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module
docroot/modules/custom/bos_migration/bos_migration.module
docroot/modules/custom/bos_migration/bos_migration.sh
docroot/modules/custom/bos_migration/src/EventSubscriber/EntityRevisionsSaveSubscriber.php
docroot/modules/custom/bos_migration/src/MigrationConfigAlter.php
docroot/modules/custom/bos_migration/src/MigrationPrepareRow.php
docroot/modules/custom/bos_migration/src/Plugin/migrate/process/SkipDraftRevision.php
docroot/themes/custom/bos_admin/bos_admin.theme

Done.
This adds manual processes to migrate the D7 workbench moderation into the D8 content moderation.
- Migrates only published nodes.
- Does not migrate (copy) media.
- Sets published status correctly for revisions.
- Sets moderation states for previous revisions correctly.
- Sets current revision and current moderated revision correctly.

End to end migration.

---

docroot/modules/custom/bos_vocab/modules/vocab_contact/templates/field--field-email.html.twig

Related to https://github.com/CityOfBoston/Iterators/issues/67

Add title for hover on email.

---

config/default/views.view.metrolist_affordable_housing.yml

Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/990

CEX: Stop truncating Lottery listing PDFs.

---

docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module

Related to https://github.com/CityOfBoston/boston.gov-d8/issues/1086

Allow missing titles for grid links.

---

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css

Issue #1015 : Department icons not centered
- Removed height
- Changed width to from a pixel unit to a percentage
- Adjusted `left-padding` to push icons closer to the center.
*TODO: Pages like [this](http://boston.lndo.site/departments/intergovernmental-relations) overlap with the icons due because some words are too long to be broken into the next line. If we want to try and address this it, it should be in another ticket. Ps. The best we can try to do is to see if can change the font-size on those title elements.

Issue #1015: Department icons not centered

---

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css

Reverting Issue #1015 from `develop` and `master`

Revert Issue #1015: Department icons not centered

---

config/default/ape.settings.yml
config/default/core.base_field_override.node.neighborhood_lookup.promote.yml
config/default/node.type.neighborhood_lookup.yml
config/default/pathauto.pattern.my_neighborhood_lookup_so_can_disable_cache_in_ape_.yml
config/default/rabbit_hole.behavior_settings.node_type_neighborhood_lookup.yml
config/default/system.performance.yml
docroot/modules/custom/bos_components/modules/bos_mnl/src/Controller/MNLRest.php
docroot/modules/custom/bos_components/modules/bos_mnl/src/Form/MNLSettingsForm.php
docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLDeleteAll.php
docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessCleanup.php
docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessImport.php
docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessUpdate.php

Backend configs for mnl entity.

---

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css

Accessibility was removed from UAT as the deploy branch and a tag was used instead.

Recaptcha deploy to UAT - Trigger Travis

---

composer.json
composer.lock
scripts/local/sync.sh

Adds a patch for jsonapi to composer.json. Patch fixes issue where uninstalling a module which contains definitions for a paragraph, removes the paragraph entities - but does not (because of complexity) remove those deleted entities from the list of entities allowed in an entity_reference field on some other entity.  
We has this issue uninstalling bos_link_collections which correctly uninstalled a number of grid-link paragraphs. However this left other entities (e.g. the Article content type) with an entity_reference type field and which include/allow the (now) deleted paragraph entities. Some poor coding in jsonapi core cause that module to crash when updating caches and makes drush largely unusable.

Maintenance 07 01 2020

---

config/default/views.view.emergency_alerts.yml
config/default/views.view.site_alerts.yml
docroot/modules/custom/bos_core/bos_core.module

This sets all site_alert and emergency_alert views to only cache output for 1 minute.  This is because content should be removed and shown on a schedule.
Also adds code to bos_core to invalidate caches when a site or emergency alert is updated.  The invalidation targets those nodes which have registered the view output in their cache-tags.
This should eliminate the need to refresh varnish caches manually on production when a site_alert or emergency_alert is created, updated, or removed.  We need to test if the cache is cleared when the alert expires (b/c an update is not actually performed so the hook in bos_core wont be fired - we will rely on the cachetag expiring after 1 min and this is unclear).

Invalidates caches for all pages with alerts, when alerts are updated.

---

config/default/webform.webform.metrolist_listing.yml

Re-enable email on metrolist listing form

Re-enable email on metrolist listing form

---

config/default/field.field.node.article.body.yml
config/default/field.field.node.department_profile.body.yml
config/default/field.field.node.event.body.yml
config/default/field.field.node.post.body.yml

Make page body copy not required on all content types: unset the body field requirement on article, department, event, posts.

#618 - Make page body copy not required on all content types

---

docroot/themes/custom/bos_theme/js/cob_ckeditor.boston.js

Allow embed style images in the WYSIWYG to not auto-resize if they have a parent wrapper with the class of: ".no-resize".

Feature/#2080 - Image resizing issues

---

config/default/field.field.node.procurement_advertisement.field_awarded_by.yml
config/default/field.field.node.procurement_advertisement.field_email.yml
config/default/field.field.node.procurement_advertisement.field_phone_number.yml
config/default/field.field.node.procurement_advertisement.field_unspsc.yml
config/default/views.view.bids_rfps.yml
config/default/views.view.bos_dashboards.yml
docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--bids-rfps.html.twig
docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.module
docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--procurement-advertisement.html.twig

* #2052 - prevent pre-populating of text fields on the node edit form
* #2052 - Add new content dashboard for Procurement Advertisement
* #2052 - Add cross-search functionality to the Procurement Advertisement search.
* #2052 - hide and set a default value for the Award Date time sub-field on the node edit form
* #2052 - make a field not required: Awarded by, UNSPSC, Contact Email, Contact Phone
* #2052 - Fix for the "Not Awarded" status not showing on the bit pages
* #2052 - Add new copy for Bids & RFPs search pages cross-search functionality, rename new PA Dashboard and add menu item to Workbench menu
* #2052 - Adjust styles on Bids & RFPs search pages cross-search
* #2052 - update path for Bids & RFPs dashboard

[RELEASE TO STAGE] - #2052 - Updates to procurement advertisement content type (#2060)

---

docroot/modules/custom/bos_components/modules/bos_featured_topics/bos_featured_topics.module

Add image style to re-size backgrounds of bos_featured_topics, images are too large in size. Dropping from original to "bos_text_responsive" (scale 800px wide)

#2122 - Add image style to re-size backgrounds of bos_featured_topics

---

docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css
docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module
docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php
docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php
docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline.html.twig
docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-type.html.twig
docroot/themes/custom/bos_theme/dist/js/all.js

* #2218 - "Transactions grid" component display broken on "how-to" pages.
Remove old JS function that would copy and duplicate a breadcrumb element to any and every article element.
* #2089 - If Housing 'Project Type' is blank, leave sub-type blank in sidebar
* #1763 - Add Button to Open Space + Housing: Homeownership Project Type Components
* #2078 - Make Disposition Projects in an "Awarded" stage show up as in "City Planning" ...
* #1971 - Remove "We're funding this project..." line of text from development-only fund...
* #2077 - Remove Developer Profile from Inactive Parcels
* #2077 - Remove Developer Profile from Inactive Parcels. Also including a fix for the DateTime issue on Meeting notices.

[RELEASE TO STAGE] - Release/2021-11-29_a (#2265)

---

config/acquia_dev/purge.logger_channels.yml
config/acquia_dev/purge.plugins.yml
config/acquia_prod/purge.logger_channels.yml
config/acquia_prod/purge.plugins.yml
config/acquia_stage/purge.logger_channels.yml
config/acquia_stage/purge.plugins.yml
config/default/config_split.config_split.acquia_dev.yml
config/default/config_split.config_split.acquia_prod.yml
config/default/config_split.config_split.acquia_stage.yml
config/local/config_ignore.settings.yml

Adds the purger config to each environment so that when configs are imported the purgers are not removed.

hotfix: add purger to config_split across environments

---

docroot/modules/custom/bos_core/src/EventSubscriber/AccountSubscriber.php

This earlier update forced the PreferredAdminLangcode to english.
As a result editors can only edit the english version of content.
This reverts while another solution is found.

Hotfix removes forced PreferredAdminLangcode.

---

config/default/webform.webform.metrolist_listing.yml

DIG-433 - Telephone number (&date) format on metrolist_listing webform
**I cannot replicate the date issue atm.**

(develop) Allows broader telephone number format on metrolist_listing webform

---

docroot/themes/custom/bos_theme/bos_theme.theme

DIG-67  -cannot replicate this issue locally.
Seems too easy. This needs to be tested on an environment with caching set, with varnish etc etc.

(develop) Set breadcrumb to cache separately from the node.

---

config/acquia_prod/redirect_domain.domains.yml

(develop) Fix subdomain redirect in configuration for rentsmart.boston.gov

---

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php

Production bug-fix, misnamed class.

DIG-993 Contact forms on Boston.gov failing to send - hotfix

---

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php

(develop) Contact forms on Boston.gov failing to send - Hotfix

---

config/default/core.extension.yml

Previous [develop] deploy has issues.
Seems the database is not functional, so trying to add back the mysql module which some installations have been complaining about missing.

[develop] re-enabled mysql DIG-1206

---

composer.lock

@see known issues in [9.4.8 version](https://www.drupal.org/project/drupal/releases/9.4.8) of drupal/core

[develop] downgrades drupal/core to 9.4.7. DIG-1206

---

composer.lock

(develop) Reupgrades to 9.4.8 with fix in place. DIG-1206

---

config/default/core.entity_view_display.node.election_report.default.yml
config/default/core.entity_view_display.node.election_report.election_card.yml
docroot/modules/custom/bos_content/modules/node_elections/js/node_elections.js
docroot/modules/custom/bos_content/modules/node_elections/node_elections.libraries.yml
docroot/modules/custom/bos_content/modules/node_elections/node_elections.module
docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--full.html.twig
docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-area-results--election-card.html.twig
docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-card--full.html.twig
docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-contest-results--election-card.html.twig
docroot/modules/custom/bos_content/modules/node_elections/templates/taxonomy-term--elections.html.twig
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T17_52_57.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_0.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_1.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_2.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_3.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_4.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_5.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_6.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_7.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_8.xml
docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_2022_11_08T21_19_26_9.xml
docroot/themes/custom/bos_theme/dist/js/all.js

- Sorts the order of contests by sort order provided in import file (this will now align with the order in the selectbox).
- Sorting is done by javascript in module level js script. Also removed the filtering js from all.js into the same module-level js file. This js file added to the module library so that code will only be included when the election_report node is rendered (election_report node is typically embedded within an election_card paragraph which is in turn embedded within an article node).
- Background striping has been updated along with the filtering activity, by adding/removing css classes directly and not using n-child css rules (which can get confused when jquery moves elements on the page).

(develop) Display unofficial results in the same order as the ballot. DIG-1362

---

config/acquia_dev/config_ignore.settings.yml
config/acquia_stage/config_ignore.settings.yml
config/local/config_ignore.settings.yml

This can wait until next deploy cycle as it only affects non-prod environments.

(develop) election history wont get overwritten on deploy DIG-1435

---

config/default/core.extension.yml

Looks like at some point these got split into separate modules and geolocation has a dependency on them

(develop) DIG-1770 (hotfix) JQuery missing modules

---

docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig

DIG-2060 - [Adjust order of contact information in event sidebar; move down 'email' field](https://bostondoit.atlassian.net/browse/DIG-2060)

(develop) Adjust order of contact information in event sidebar - hotfix

---

docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig

DIG-2527:[ Add phone number as option in Boston.gov contact form](https://bostondoit.atlassian.net/browse/DIG-2527)

(develop) Ass phone number as option to Boston.gov contact form

---

docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php

DIG-2527 A[dd phone number as option in Boston.gov contact form](https://bostondoit.atlassian.net/browse/DIG-2605)

(develop) Add phone number as option in Boston.gov contact form (hotfix)

---

docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php
docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig

DIG-2527 [Add phone number as option in Boston.gov contact form](https://bostondoit.atlassian.net/browse/DIG-2605)

(stage) Add phone number as option in Boston.gov contact form (hotfix)

---

config/default/bos_email.settings.yml
docroot/modules/custom/bos_components/modules/bos_email/bos_email.module
docroot/modules/custom/bos_components/modules/bos_email/src/CobEmail.php
docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php
docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php
docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php

DIG-3674 [Metrolist listing form not being emailed to users.](https://bostondoit.atlassian.net/browse/DIG-3674)

(develop) Metrolist listing form not being emailed to users. (hotfix) DIG-3674

---

docroot/modules/custom/bos_components/css/component-theme.css

DIG-3979 Blue text not appearing on white background in components

(develop) Blue text not appearing on white background in components (hotfix)

---

docroot/modules/custom/bos_components/modules/bos_emergency_alerts/bos_emergency_alerts.module
docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/ApiRouter.php
docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EmergencyAlertsSubscriberBase.php
docroot/modules/custom/bos_components/modules/bos_geocoder/src/Controller/BosGeocoder.php
docroot/modules/custom/bos_core/src/Controllers/Curl/BosCurlControllerBase.php

DIG-3839 [Alert Boston API integration of Genasys with Drupal](https://bostondoit.atlassian.net/browse/DIG-3839)

DIG-3839 (hotfix) Fixes email issue

---

docroot/modules/custom/bos_components/css/component-theme.css

DIG-4170 Listing 'Intro' class text not appearing in blue background of 'formatted text' component

DIG-4170 Listing 'Intro' class text

---

docroot/modules/custom/bos_components/css/component-theme.css

DIG-4170 Listing 'Intro' class text not appearing in blue background of 'formatted text' component

(develop) DIG-4170 Listing 'Intro' class text

---

docroot/modules/custom/bos_components/modules/bos_google_cloud/bos_google_cloud.links.menu.yml
docroot/modules/custom/bos_components/modules/bos_google_cloud/bos_google_cloud.links.task.yml
docroot/modules/custom/bos_components/modules/bos_google_cloud/bos_google_cloud.routing.yml
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Controller/PromptTesterFormController.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Form/ConfigForm.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Form/PromptTesterForm.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/GcGenerationConfig.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Services/GcTextRewriter.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Services/GcTextSummarizer.php
docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Services/GcTranslation.php
docroot/modules/custom/bos_core/src/Controllers/Curl/BosCurlControllerBase.php

DIG-4280 [Add Gen-AI prompt testing ](https://bostondoit.atlassian.net/browse/DIG-4280)

(develop) (hotfix) Add Gen-AI prompt testing DIG-4280

---

docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.menu.yml
docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.routing.yml
docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php

chore: BH admin page sf sync improvements
- Sets permissions on the SF/BH Admin page, 
- improves page layout, 
- adds resilience to SF connectivity issues 
- relocates config page link in menu system.

(develop) BH admin page sf sync improvements

---

docroot/modules/custom/bos_components/modules/bos_sidebar/templates/paragraph--sidebar-item-w-icon.html.twig

Fix Google Translate Spanish translation error for email addresses

DIG-4874 Fix Google Translate Spanish translation error for email addresses

---

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/metrolist.libraries.yml

Potential fix to bundles not loading correctly in previously deployed version of dev as well as missing css around filter panel elements.

(dev) DIG-5067-Updated-Libraries-YML-to-Include-All-Bundles
