CityOfBoston/boston.gov-d8

composer.json, docroot/profiles/bos_profile/bos_profile.info.yml, docroot/profiles/bos_profile/bos_profile.install, docroot/sites/default/settings/default.local.settings.php, docroot/themes/custom/bos_theme/images/apple-touch-icon-precomposed.png, docroot/themes/custom/bos_theme/images/apple-touch-icon.png
Adds logic to switch site-environment indicator, and updates module selection based on environment setting.
=> Modifies the profile to allow the environment setting and metatag.

scripts/doit/doit, scripts/phing/tasks/setup.xml
Modifications to the install part of the D8 tooling.
=> Install cleanup

docroot/modules/custom/bos_migration/config/install/migrate_plus.migration.paragraph__bos311.yml, docroot/modules/custom/bos_migration/config/install/migrate_plus.migration.paragraph__list.yml
Also fixes bos311 default_bundle.
=> Map field_list D7 db columns to D8 structure.

composer.json, composer.lock
- also removes patch for 8.5.7 (core)
- composer.lock also updates a number of contrib modules.
=> Updates to drupal/core 8.6.1.

config/default/core.extension.yml, config/default/node.type.article.yml, docroot/modules/custom/bos_vocab/modules/vocab_news_tags/config/install/language.content_settings.taxonomy_term.news_tags.yml, docroot/modules/custom/bos_vocab/modules/vocab_news_tags/config/install/taxonomy.vocabulary.news_tags.yml, docroot/modules/custom/bos_vocab/modules/vocab_news_tags/vocab_news_tags.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_news_tags/vocab_news_tags.install
Adds a module to provide configuration for the `news_tags` vocabulary.
=> Create vocab_news_tags module

config/default/core.extension.yml, config/default/field.field.node.event.field_event_type.yml, docroot/modules/custom/bos_vocab/modules/vocab_event_type/config/install/language.content_settings.taxonomy_term.event_type.yml, docroot/modules/custom/bos_vocab/modules/vocab_event_type/config/install/taxonomy.vocabulary.event_type.yml, docroot/modules/custom/bos_vocab/modules/vocab_event_type/vocab_event_type.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_event_type/vocab_event_type.install
Create module to provide configuration for `event_type` taxonomy.
=> Create vocab_event_type module

config/default/core.extension.yml, config/default/taxonomy.vocabulary.icons.yml, docroot/modules/custom/bos_vocab/modules/vocab_icons/config/install/language.content_settings.taxonomy_term.icons.yml, docroot/modules/custom/bos_vocab/modules/vocab_icons/config/install/taxonomy.vocabulary.icons.yml, docroot/modules/custom/bos_vocab/modules/vocab_icons/vocab_icons.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_icons/vocab_icons.install
Creates module to provide configs for `icons` taxonomy.
=> Create vocab_icons module.

config/default/core.extension.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/core.entity_form_display.taxonomy_term.newsletters.default.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/core.entity_view_display.taxonomy_term.newsletters.default.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/field.field.taxonomy_term.newsletters.field_id.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/field.storage.taxonomy_term.field_id.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/language.content_settings.taxonomy_term.newsletters.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/config/install/taxonomy.vocabulary.newsletters.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/vocab_newsletters.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_newsletters/vocab_newsletters.install
Adds module that provides config for `newsletters`vocabulary.
=> Add module providing newsletters taxonomy

config/default/core.extension.yml, docroot/modules/custom/bos_vocab/modules/vocab_ma_general_law/config/install/language.content_settings.taxonomy_term.massachusetts_general_law.yml, docroot/modules/custom/bos_vocab/modules/vocab_ma_general_law/config/install/taxonomy.vocabulary.massachusetts_general_law.yml, docroot/modules/custom/bos_vocab/modules/vocab_ma_general_law/vocab_ma_general_law.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_ma_general_law/vocab_ma_general_law.install
Adds module that provides config for `ma_general_law` vocabulary.
=> Add module for massachusetts_general_law vocabulary

config/default/core.extension.yml, config/default/field.field.taxonomy_term.maps_esri_feed.field_map_default_coordinates.yml, config/default/field.storage.taxonomy_term.field_map_default_coordinates.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/core.entity_form_display.taxonomy_term.maps_esri_feed.default.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/core.entity_view_display.taxonomy_term.maps_esri_feed.default.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/field.field.taxonomy_term.maps_esri_feed.field_map_default_coordinates.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/field.field.taxonomy_term.maps_esri_feed.field_map_esri_feed.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/field.storage.taxonomy_term.field_map_default_coordinates.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/field.storage.taxonomy_term.field_map_esri_feed.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/language.content_settings.taxonomy_term.maps_esri_feed.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/config/install/taxonomy.vocabulary.maps_esri_feed.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/vocab_map_esri.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_map_esri/vocab_map_esri.install
Adds module that provides config for esri map vocabulary.
=> Create module providing maps_esri_feed taxonomy configs

docroot/modules/custom/bos_components/modules/bos_311/bos_311.install, docroot/modules/custom/bos_components/modules/bos_bid/bos_bid.install, docroot/modules/custom/bos_components/modules/bos_city_score/bos_city_score.install, docroot/modules/custom/bos_components/modules/bos_fyi/bos_fyi.install, docroot/modules/custom/bos_components/modules/bos_link/bos_link.install, docroot/modules/custom/bos_components/modules/bos_sidebar/bos_sidebar.install, docroot/modules/custom/bos_components/modules/bos_text/bos_text.install, docroot/modules/custom/bos_components/modules/bos_time/bos_time.install, docroot/modules/custom/bos_core/bos_core.module
Adds code into boston core to install icons into shared files folder for paragraphs modules.
=> Standard icon install

config/default/editor.editor.basic_html.yml, config/default/editor.editor.filtered_html.yml, config/default/editor.editor.full_html.yml, config/default/filter.format.basic_html.yml, config/default/filter.format.filtered_html.yml, config/default/filter.format.full_html.yml, config/default/filter.format.restricted_html.yml, config/default/linkit.linkit_profile.bos_settings_linkit_editor.yml
Updates text formats + linkit configs to match what we have in D7
=> Update WYSIWYG and related settings

composer.json, composer.lock, config/default/core.extension.yml, config/default/file_mdm.file_metadata_plugin.getimagesize.yml, config/default/file_mdm.settings.yml, config/default/file_mdm_exif.file_metadata_plugin.exif.yml, config/default/imagemagick.file_metadata_plugin.imagemagick_identify.yml, config/default/imagemagick.settings.yml, config/default/system.image.yml
Installs and configures imagemagick to be the default image processing toolkit.
=> Install and enable imagemagick processing toolkit

scripts/phing/tasks/deploy.xml
=> Recreates Phing deploy properties.

docroot/modules/custom/bos_components/modules/bos_text/bos_text.module, docroot/themes/custom/bos_admin/bos_admin.theme, docroot/themes/custom/bos_theme/bos_theme.theme
Replaces some custom functions with drupal core functions and makes fix_attributes function more robust.
=> Housekeeping

.travis.yml, composer.json, config/default/core.entity_view_display.node.person_profile.listing.yml, docroot/modules/custom/bos_components/modules/bos_grid/bos_grid.module, docroot/modules/custom/bos_components/modules/bos_grid/templates/node--person-profile--listing.html.twig, docroot/modules/custom/bos_content/modules/node_landing_page/node_landing_page.module, docroot/modules/custom/bos_content/modules/node_landing_page/templates/node--landing-page--full.html.twig, docroot/modules/custom/bos_content/modules/node_person_profile/node_person_profile.module, patches/imagemagikToolkit_001.patch, scripts/phing/phing-boston.yml, scripts/phing/tasks/setup.xml
Fixes some node templating.
Improves deploy.
Updates landing page (node/21)
Removes warnings and errors.
=> Migration2

.lando.yml, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
Fixes #373 
- template, preprocess, and css tweaks to get main menu functional
=> Fix menus - Issue 373

patches/imageMagick_svg_parse.patch
Hotfix style - fixes annoying message on admin pages..
=> Fixes patch.

docroot/modules/custom/bos_components/modules/bos_hero_image/templates/paragraph--hero-image.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/snippets/logo.html.twig
Aligns with recent changes to Drupal 7 site.
=> Issue #291 - B Logo on small screens.

docroot/modules/custom/bos_core/bos_core.module
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/396
=> Remove client side validation for required fields.

config/default/core.entity_form_display.paragraph.bos_signup_emergency_alerts.default.yml, config/default/core.entity_view_display.paragraph.bos_signup_emergency_alerts.default.yml, config/default/core.entity_view_display.taxonomy_term.features.article.yml, config/default/core.entity_view_display.taxonomy_term.features.contact.yml, config/default/core.entity_view_display.taxonomy_term.features.default.yml, config/default/core.entity_view_display.taxonomy_term.features.department_listing.yml, config/default/core.entity_view_display.taxonomy_term.features.popup_icon.yml, config/default/core.entity_view_display.taxonomy_term.features.published_by.yml, config/default/core.entity_view_display.taxonomy_term.features.sidebar_right.yml, config/default/field.field.paragraph.bos_signup_emergency_alerts.field_icon.yml, config/default/field.field.paragraph.transactions.field_icon.yml, config/default/field.field.taxonomy_term.features.field_icon.yml, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/templates/paragraph--bos-signup-emergency-alerts.html.twig, docroot/modules/custom/bos_vocab/modules/vocab_features/templates/taxonomy-term--features--sidebar-right.html.twig, docroot/sites/default/files/readme.md, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Implements field_icon for para emergency alerts signup and taxonomy features, plus fixes templating for display and contextual editors.
=> Pretesting 408 2

config/default/field.field.node.department_profile.field_published_date.yml, config/default/field.field.node.department_profile.field_updated_date.yml
Partially fixes https://github.com/CityOfBoston/boston.gov-d8/issues/423
=> Make published and updated dates optional.

config/default/core.entity_form_display.paragraph.card.default.yml, config/default/core.entity_view_display.paragraph.card.default.yml, config/default/core.entity_view_display.paragraph.grid_of_cards.default.yml, config/default/field.field.paragraph.card.field_thumbnail.yml, docroot/modules/custom/bos_components/modules/bos_card/bos_card.module, docroot/modules/custom/bos_components/modules/bos_card/templates/paragraph--card.html.twig, docroot/modules/custom/bos_components/modules/bos_card/templates/paragraph--grid-of-cards.html.twig, docroot/sites/default/files/readme.md
Makes the thumbnail images in cards and grid of cards responsive.
=> Cards images - #408

config/default/core.entity_form_display.media.image.default.yml, config/default/core.entity_form_display.media.image.media_browser.yml, config/default/core.entity_form_display.node.program_initiative_profile.default.yml, config/default/core.entity_form_display.node.topic_page.default.yml, config/default/core.entity_form_display.user.user.default.yml, config/default/core.entity_view_display.media.image.embedded.yml, config/default/core.entity_view_display.media.image.media_library.yml, config/default/core.entity_view_display.media.image.thumbnail.yml, config/default/core.entity_view_display.node.program_initiative_profile.default.yml, config/default/core.entity_view_display.node.topic_page.featured_topics.yml, config/default/core.entity_view_display.node.topic_page.listing.yml, config/default/core.entity_view_display.node.topic_page.listing_long.yml, config/default/core.entity_view_display.user.user.compact.yml, config/default/core.entity_view_display.user.user.default.yml, config/default/field.field.media.image.image.yml, config/default/field.field.node.program_initiative_profile.field_program_logo.yml, config/default/field.field.node.topic_page.field_thumbnail.yml, config/default/field.field.user.user.user_picture.yml, config/default/image.style.logo_square_a_mobile.yml, config/default/image.style.logo_square_b_tablet.yml, config/default/image.style.logo_square_c_desktop_1x.yml, config/default/image.style.logo_square_d_full_1x.yml, config/default/image.style.media_fixed_height_100px_.yml, config/default/responsive_image.styles.logo_images.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_content/modules/node_topic_page/node_topic_page.module, docroot/sites/default/files/readme.md
Final commit for #408 I hope.
- Images for guides node listing display.
- program_logo image on pip node.
- User object image displays.
- Media:image object image displays.
=> Pretesting 408 featured items

docroot/modules/custom/bos_migration/bos_migration.sh, docroot/modules/custom/bos_migration/src/MigrationFixes.php
Small fix to ensure list view_name and view_display values are translated from D7 view/display naming to our D8 view/display naming.
=> Updates MigrationFixes class to convert listView values from D7->D8.

config/default/views.view.public_notice.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.public_notice.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/node--public-notice--listing.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/node--public-notice--listing.tpl.php, docroot/modules/custom/bos_components/modules/bos_list/templates/paragraph--list.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--public-notice.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view-unformatted--public-notice.html.twig, docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/437
=> Public Notices View - Issue 437

config/default/core.entity_form_display.paragraph.hero_image.default.yml, config/default/field.field.node.article.field_components.yml, config/default/field.field.paragraph.list.field_list.yml, config/default/pathauto.pattern.department_profile_pattern.yml, config/default/pathauto.settings.yml, docroot/modules/custom/bos_components/modules/bos_grid/templates/paragraph--grid-of-topics.html.twig, docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module, docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module, docroot/themes/custom/bos_theme/bos_theme.theme
#431 
- Path-auto logic and config
- Fixes some reversions
- Removes legacy image handling code
- Completes data range on site_alert functionality.
=> Pretesting 2

config/default/core.entity_form_display.node.event.default.yml, config/default/core.entity_view_display.node.event.default.yml, config/default/field.field.node.event.field_intro_text.yml, config/default/views.view.calendar.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.calendar.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.public_notice.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/node--event--calendar-listing.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/node--event--calendar-listing.tpl.php, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view-unformatted--calendar.html.twig, docroot/modules/custom/bos_content/modules/node_event/config/install/core.entity_form_display.node.event.default.yml, docroot/modules/custom/bos_content/modules/node_event/config/install/core.entity_view_display.node.event.default.yml, docroot/modules/custom/bos_content/modules/node_event/config/install/field.field.node.event.field_thumbnail.yml, docroot/modules/custom/bos_content/modules/node_event/node_event.module
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/453
=> Events view - Issue 453

docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig, docroot/modules/custom/bos_content/modules/node_how_to/node_how_to.module, docroot/modules/custom/bos_content/modules/node_post/node_post.module, docroot/modules/custom/bos_content/modules/node_program_initiative_profile/templates/node--program-initiative-profile.html.twig, docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module, docroot/modules/custom/bos_content/modules/node_tabbed_content/node_tabbed_content.module, docroot/modules/custom/bos_content/modules/node_topic_page/templates/node--topic-page.html.twig, docroot/modules/custom/bos_migration/bos_migration.sh, docroot/themes/custom/bos_admin/bos_admin.theme, docroot/themes/custom/bos_theme/bos_theme.libraries.yml, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/js/inpage-menu.boston.js, docroot/themes/custom/bos_theme/js/tabbed-page.boston.js, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
=> Pre test 3

.travis.yml, docroot/modules/custom/bos_migration/src/MigrationConfigAlter.php, docroot/modules/custom/bos_migration/src/Plugin/migrate/process/LinkUriExt.php, docroot/sites/default/settings/default.local.settings.php, docroot/themes/custom/bos_theme/templates/menu/menu--menu-main-menu.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/456
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/458
=> Process plugin for sidebar links with <nolink> uri

config/default/views.view.transactions.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/config/install/field.field.paragraph.list.field_list.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.transactions.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/node--transaction--listing.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/node--transaction--listing.tpl.php, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--transactions.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/451
=> Transaction View on List component - Issue 451

config/default/core.entity_form_display.node.status_item.default.yml, config/default/core.entity_view_display.node.status_item.default.yml, config/default/core.entity_view_display.node.status_item.listing_long.yml, config/default/core.entity_view_display.paragraph.list.default.yml, config/default/field.field.node.status_item.field_weight.yml, config/default/field.storage.node.field_weight.yml, config/default/views.view.content.yml, config/default/views.view.status_items.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/core.entity_view_display.paragraph.list.default.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.status_items.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.transactions.yml, docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/bos_components/modules/bos_messages/templates/paragraph--message-for-the-day--listing.html.twig, docroot/modules/custom/bos_content/bos_content.info.yml, docroot/modules/custom/bos_content/config/install/field.storage.node.field_weight.yml, docroot/modules/custom/bos_content/modules/node_status_item/config/install/core.entity_form_display.node.status_item.default.yml, docroot/modules/custom/bos_content/modules/node_status_item/config/install/core.entity_view_display.node.status_item.default.yml, docroot/modules/custom/bos_content/modules/node_status_item/config/install/core.entity_view_display.node.status_item.listing_long.yml, docroot/modules/custom/bos_content/modules/node_status_item/config/install/field.field.node.status_item.field_weight.yml, docroot/modules/custom/bos_content/modules/node_status_item/config/install/language.content_settings.node.status_item.yml, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.info.yml, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module, docroot/modules/custom/bos_content/modules/node_status_item/templates/viewfield-item--field-list--status-items.html.twig, docroot/modules/custom/bos_migration/bos_migration.sh, docroot/modules/custom/bos_migration/src/MigrationFixes.php, docroot/themes/custom/bos_admin/css/bos_admin.css, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/js/inpage-menu.boston.js
Removes translation settings.
Adds some migration config changes.
Fixes iterators person_profile position title Issue #30.
=> List views

config/default/pathauto.settings.yml, config/default/views.view.content.yml, docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module
=> Fixes PathAuto.

docroot/modules/custom/bos_components/modules/bos_list/templates/views-exposed-form--public-notice.html.twig
Fixes https://github.com/CityOfBoston/Iterators/issues/54
=> Public notices filters for mobile

config/default/views.view.public_notice.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.news_landing.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.public_notice.yml, docroot/modules/custom/bos_components/modules/bos_list/config/install/views.view.transactions.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/bef-checkboxes-field-contact-target-id.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/checkboxes-field-contact-target-id.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/fieldset-field-contact-target-id.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/547
=> Public Notice Views filters (autocomplete vs checkboxes)

docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module
This is a WIP related to https://github.com/CityOfBoston/Iterators/issues/44
=> Public Notice node updates

config/default/core.entity_view_display.node.event.default.yml, config/default/field.field.node.person_profile.field_political_party.yml, config/default/field.field.node.person_profile.field_year_elected.yml, docroot/modules/custom/bos_components/modules/bos_link/bos_link.module, docroot/modules/custom/bos_content/modules/node_event/templates/field--node--field-event-type--event.html.twig, docroot/modules/custom/bos_content/modules/node_person_profile/config/install/field.field.node.person_profile.field_political_party.yml, docroot/modules/custom/bos_content/modules/node_person_profile/config/install/field.field.node.person_profile.field_year_elected.yml, docroot/modules/custom/bos_migration/bos_migration_sync.sh, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/user/page--user--login.html.twig
More iterators issues:
Plus script for automated migration.
=> Iterators du

config/default/core.entity_view_display.node.person_profile.default.yml, config/default/core.entity_view_display.node.program_initiative_profile.default.yml, config/default/core.entity_view_display.taxonomy_term.contact.department_listing.yml, config/default/image.style.person_photo_profile_large_360x360_.yml, config/default/image.style.person_photo_profile_mid_285x582_.yml, config/default/responsive_image.styles.person_profile_photo.yml, config/default/views.view.topic_landing_page.yml, docroot/modules/custom/bos_components/modules/bos_grid/bos_grid.module, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--topic-landing-page.html.twig, docroot/modules/custom/bos_content/modules/node_listing_page/templates/node--listing-page.html.twig, docroot/modules/custom/bos_content/modules/node_program_initiative_profile/node_program_initiative_profile.module, docroot/modules/custom/bos_content/modules/node_program_initiative_profile/templates/node--program-initiative-profile.html.twig, docroot/modules/custom/bos_content/modules/node_topic_page/node_topic_page.module, docroot/modules/custom/bos_migration/bos_migration.sh, docroot/modules/custom/bos_migration/src/MigrationFixes.php, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Iterators issues: 
Plus fixes for migration scripts.
=> Iterators du 3

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Related to https://github.com/CityOfBoston/Iterators/issues/72#issuecomment-525872941
=> Fix menu links for expanded sidebar.

config/default/core.entity_form_display.paragraph.document.default.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/node--transaction--listing.html.twig
Related to https://github.com/CityOfBoston/Iterators/issues/69
=> Fix transaction links on Pay and Apply

config/default/core.entity_view_display.paragraph.drawers.default.yml, config/default/views.view.news_and_announcements.yml, docroot/modules/custom/bos_components/modules/bos_drawers/config/install/core.entity_view_display.paragraph.drawers.default.yml, docroot/modules/custom/bos_components/modules/bos_news_and_announcements/templates/paragraph--news-and-announcements.html.twig, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Related to https://github.com/CityOfBoston/Iterators/issues/59
=> Fix Place Profile difference + News & Announcements view

config/default/core.entity_view_display.node.department_profile.department_listing.yml, config/default/views.view.departments_listing.yml, docroot/modules/custom/bos_content/modules/node_event/node_event.module, docroot/modules/custom/bos_migration/bos_migration.sh, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> Iterators du 4

docroot/modules/custom/bos_components/modules/bos_list/bos_list.module
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/555
=> Change action url of exposed View filters.

config/default/core.entity_form_display.paragraph.message_for_the_day.default.yml, config/default/field.field.paragraph.internal_link.field_internal_link.yml, config/default/views.view.status_items.yml, docroot/modules/custom/bos_components/modules/bos_city_score/tests/CityScoreTest.php, docroot/modules/custom/bos_migration/src/MigrationFixes.php, docroot/themes/custom/bos_theme/bos_theme.theme, tests/phpunit/DrupalBootstrap.php, tests/phpunit/SettingsTest.php
- Adds cityscore phpunit test code from d7.
- improves some forms interaction.
=> Du general

docroot/themes/custom/bos_theme/bos_theme.theme
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/595
=> Ensure page ID is added to all pages for in-page nav.

docroot/modules/custom/bos_core/src/BosCoreCssSwitcherService.php, docroot/modules/custom/bos_core/src/Commands/BosCoreCommands.php
Fixes drush command per issue #413.
=> Updates bcss drush command per issue #413.

docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/templates/input-title.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/views-exposed-form--topic-landing-page.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--topic-landing-page.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/631
=> Exposed filter styling for Guides view - Issue 631

config/default/core.entity_form_display.paragraph.columns.default.yml, config/default/core.entity_view_display.file.image.entity_browser.yml, config/default/core.entity_view_display.file.image.entity_browser_document.yml, config/default/core.entity_view_display.file.image.entity_browser_icon.yml, config/default/core.entity_view_display.node.department_profile.article.yml, config/default/core.entity_view_display.node.department_profile.card.yml, config/default/core.entity_view_display.paragraph.columns.default.yml, config/default/core.entity_view_mode.file.entity_browser.yml, config/default/core.entity_view_mode.file.entity_browser_document.yml, config/default/core.entity_view_mode.file.entity_browser_icon.yml, config/default/entity_browser.browser.media_entity_browser.yml, config/default/image.style.media_fixed_width_250px.yml, config/default/views.view.wysiwyg_entity_browser.yml, docroot/modules/custom/bos_components/modules/bos_messages/templates/paragraph--message-for-the-day--listing.html.twig, docroot/modules/custom/bos_migration/src/MigrationFixes.php, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/content/media.html.twig
=> Background images

docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_components/modules/bos_list/templates/field--field-component-title--video--mode--full.html.twig, docroot/modules/custom/bos_content/modules/node_person_profile/templates/node--person-profile--listing.html.twig, docroot/themes/custom/bos_theme/bos_theme.theme
Fixes https://github.com/CityOfBoston/Iterators/issues/70#issuecomment-528430360
=> Fix video title style.

docroot/modules/custom/bos_components/modules/bos_featured_topics/templates/paragraph--featured-topics.html.twig
Fixes https://github.com/CityOfBoston/Iterators/issues/49
=> Wrong colors / order for featured_topics Paragraph 

docroot/modules/custom/bos_migration/src/FilesystemReorganizationTrait.php, docroot/modules/custom/bos_migration/src/MediaEntityTrait.php, docroot/modules/custom/bos_migration/src/MemoryManagementTrait.php, docroot/modules/custom/bos_migration/src/MigrationFixes.php, docroot/modules/custom/bos_migration/src/Plugin/migrate/process/CreateMediaEntity.php, docroot/modules/custom/bos_migration/src/Plugin/migrate/process/RichTextToMediaEmbed.php
=> Migration fixes.

docroot/modules/custom/bos_components/modules/bos_video/bos_video.module
This is already on `dev` via a hotfix.
This PR is mainly to bring new settings from the private repo to `dev` on Acquia.
=> Fixes bos_video when background image is missing.

config/default/autologout.settings.yml, config/default/core.entity_form_display.paragraph.events_and_notices.default.yml, config/default/core.entity_form_display.paragraph.news_and_announcements.default.yml, config/default/core.extension.yml, config/default/field.field.paragraph.news_and_announcements.field_link.yml, config/default/lightning_core.versions.yml, docroot/modules/custom/bos_components/modules/bos_featured_topics/bos_featured_topics.module, docroot/modules/custom/bos_content/modules/node_topic_page/node_topic_page.module, docroot/modules/custom/bos_migration/bos_migration.sh, docroot/modules/custom/bos_migration/src/FilesystemReorganizationTrait.php, docroot/modules/custom/bos_migration/src/MigrationConfigAlter.php, docroot/modules/custom/bos_migration/src/MigrationFixes.php
=> Adds a reliable sequence number to the featured topics paragraph.

docroot/modules/custom/bos_components/modules/bos_list/templates/node--event--calendar-listing.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/871
=> Convert event date fields.

config/default/salesforce.settings.yml, config/default/views.view.calendar.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/871
=> Fix calendar grouping

docroot/modules/custom/bos_components/modules/bos_link/bos_link.module
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/890
=> Make external links buttons for cta view mode.

config/default/core.entity_view_display.paragraph.fyi.default.yml, docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
- issue #909 large images in text fields.
- issue #902 icon missing in FYI.
- issue #927  can't save public notices.
=> Hotfix launch

docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/951
=> Add contact_url.

config/default/views.view.metrolist_affordable_housing.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/952
=> CEX: Change Taxonomy term filter label to Neighborhood.

config/default/views.view.metrolist_affordable_housing.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/953
=> CEX: Add sortable columns to Lottery view.

composer.json, composer.lock, config/default/core.entity_form_display.node.event.default.yml, config/default/core.entity_form_display.node.post.default.yml, config/default/core.entity_form_display.node.public_notice.default.yml, config/default/views.view.entity_reference_filters.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/920
=> Patch entity reference Views filters.

.gitignore, config/default/views.view.metrolist_affordable_housing.yml, docroot/modules/custom/bos_components/modules/bos_list/templates/fieldset-bef-checkboxes.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/1006
=> Metrolist sort and filters - Issue 1006

config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_content/modules/node_event/templates/node--event--featured-item.html.twig
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/960
=> Events & Notices fixes

config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices.html.twig
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/926
=> Fix View sorting so both Public Notices and Events to appear in Events & Notices - Issue 926

config/default/core.entity_view_display.node.program_initiative_profile.default.yml, config/default/salesforce_mapping.salesforce_mapping.metrolist_affordable_housing.yml, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> Adds filter to salesforce import.

config/default/views.view.rss_feeds.yml, docroot/modules/custom/bos_components/modules/bos_commissions/bos_commissions.module, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> Issue #1010/981

config/default/views.view.events_and_notices.yml, config/develop/config_devel.settings.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/926#issuecomment-562206097
=> Change amount of time it takes for Notice and Event to drop off list - Issue 926

docroot/modules/custom/bos_components/modules/bos_news_and_announcements/templates/views-view-fields--news-and-announcements.html.twig
https://github.com/CityOfBoston/boston.gov-d8/issues/1040
=> Fix html endcoding

docroot/modules/custom/bos_components/modules/bos_card/bos_card.module
=> Fixes clone for grid of cards.

docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module, docroot/modules/custom/bos_content/modules/node_public_notice/templates/node--public-notice--listing.html.twig, docroot/modules/custom/bos_core/bos_core.module
=> Deploy to Stage

config/default/core.entity_view_display.node.post.listing.yml
=> Fixes carriage return on post listing. Issue #1061. #1077.

config/default/views.view.news_landing.yml
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/1073
=> CEX: Enable reset button for news_landing view.

config/default/core.entity_view_display.paragraph.grid_links.default.yml, config/develop/config_devel.settings.yml
Fixes ellipsis not applying return on paragraphs. #1059.
=> Fixes ellipsis not applying return on paragraphs

config/default/views.view.public_notice.yml, docroot/modules/custom/bos_content/modules/node_listing_page/node_listing_page.module, docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module
=> Public notice dates

config/default/ape.settings.yml, config/default/views.view.public_notice.yml, config/default/views.view.status_items.yml
=> Issue 1111

config/default/user.role.content_editor.yml, config/default/views.view.public_notice.yml
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/1129
=> CEX: Let content_editor set draft to needs review.

config/default/views.view.bids_rfps.yml
Wrong no content text display. #1066
=> Fix for issue #1066. 

docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/sites/default/services.yml
=> Cors date fix

config/default/views.view.news_and_announcements.yml
Fixes https://github.com/CityOfBoston/boston.gov-d8/issues/1113
=> Do not link title field to content for News & Announcements view > related display

config/default/salesforce_mapping.salesforce_mapping.metrolist_affordable_housing.yml, docroot/modules/custom/bos_content/modules/node_metrolist/src/EventSubscriber/SalesforceEventsSubscriber.php
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/1143
=> Map Salesforce locations to our existing Neighborhoods taxonomy - Issue 1143

config/default/views.view.public_notice.yml
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/547
=> CEX: Change public notice filter to checkboxes.

docroot/modules/custom/bos_components/modules/bos_featured_topics/bos_featured_topics.module, docroot/modules/custom/bos_components/modules/bos_featured_topics/templates/paragraph--featured-topics.html.twig
Related to https://github.com/CityOfBoston/boston.gov-d8/issues/816
=> Fix order of featured guides - Issue 816

config/default/language.negotiation.yml, config/default/system.site.yml, docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/paragraph_summary/paragraph_summary.module
=> Status items

config/default/core.entity_view_display.node.event.default.yml, docroot/modules/custom/bos_components/bos_components.module, docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/bos_components/modules/bos_messages/src/Plugin/Field/FieldWidget/MODRecurWidget.php, docroot/modules/custom/bos_content/modules/node_event/node_event.module, docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module, docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module, docroot/themes/custom/bos_admin/css/forms.css
=> Status items & default language

.lando.yml, config/default/core.entity_form_display.paragraph.web_app.default.yml, config/default/core.entity_view_display.paragraph.message_for_the_day.listing.yml, config/default/core.entity_view_display.paragraph.web_app.default.yml, config/default/field.field.paragraph.web_app.field_app_name.yml, config/default/field.storage.paragraph.field_recurrence.yml, config/default/node_status_item.settings.yml, config/default/paragraphs.paragraphs_type.web_app.yml, config/default/user.role.metrolist_editor.yml, config/default/views.view.metrolist_affordable_housing.yml, config/default/views.view.status_items.yml, config/default/workflows.workflow.unmanaged_workflow.yml, docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/bos_components/modules/bos_messages/css/mod-recur-widget.css, docroot/modules/custom/bos_components/modules/bos_messages/src/Plugin/Field/FieldWidget/MODRecurWidget.php, docroot/modules/custom/bos_content/modules/node_status_item/config/install/node_status_item.settings.yml, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module, scripts/local/lando-build-drupal.sh, scripts/local/lando-build-node.sh, scripts/local/lando-post-start.sh
=> Metro-list and Status Items

docroot/modules/custom/bos_components/modules/bos_web_app/bos_web_app.info.yml, docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module, scripts/.config.yml, scripts/deploy/travis_deploy.sh
=> Quick fixes.

docroot/modules/custom/bos_linkit_extension/bos_linkit_extension.module
Issue #1164 Email link not working and has bad characters in it.
=> Fix for issue #1164.

.travis.yml, config/default/views.view.workbench_edited.yml, scripts/.config.yml
=> #1101 view on workbench

config/default/views.view.calendar.yml, docroot/modules/custom/bos_content/modules/node_event/node_event.module, docroot/modules/custom/bos_content/modules/node_event/templates/snippets/detail-item.html.twig
=> Updates calendar view to use recurring dates for events.

config/default/core.entity_view_display.node.procurement_advertisement.default.yml, config/default/core.entity_view_display.node.program_initiative_profile.listing.yml, config/default/field.field.node.procurement_advertisement.field_related_links.yml, config/default/views.view.bids_rfps.yml, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.module
Create new branch to merge into procurement
=> Procurement ui

docroot/themes/custom/bos_admin/bos_admin.theme, docroot/themes/custom/bos_theme/bos_theme.libraries.yml, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/js/moderation_sidebar.boston.js, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
=> Adds Status-bar #1090

config/default/core.entity_form_display.node.procurement_advertisement.default.yml, config/default/views.view.bids_rfps.yml
Changes to procurement views contact required field and bids date
=> Changes to procurement

docroot/modules/custom/bos_content/modules/node_script_page/templates/node--script-page.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> css updates for image and breadcrumb locations.

docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--procurement-advertisement.html.twig
[] breadcrumb added to detail page
=> Added breadcrumb to procurement detail page

docroot/modules/custom/bos_components/modules/bos_messages/bos_messages.module, docroot/modules/custom/paragraph_summary/paragraph_summary.module
GUI updates prompted by issues 02/07/2020.
=> Improves editor experience for status_items.

docroot/themes/custom/bos_admin/bos_admin.theme
=> Hotfix issue

docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.module, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--procurement-advertisement--listing.html.twig
=> Procurement changes to Awarded Field and Project name required

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Reverting Issue #1015 from develop and master
=> Revert Issue #1015: Department icons not centered

config/default/views.view.bids_rfps.yml, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--procurement-advertisement.html.twig
Removed Supplier Portal and Changed Search Procurement Title Issuesa #1251  #1218
=> Procurement

.travis.yml
Improves messaging in slack during deployment.
=> Updates slack posting during deploy workflow.

.travis.yml, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.install, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.module, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--procurement-advertisement.html.twig, scripts/.config.yml
Trying to force Travis to kick in
=> Procurement - Bid Amount push to UAT PR

config/default/core.entity_form_display.node.event.default.yml, config/default/views.view.calendar.yml, docroot/modules/custom/bos_content/modules/node_event/config/install/core.entity_form_display.node.event.default.yml, docroot/modules/custom/slackposter/slackposter.info.yml
- Issue #1276 
- slackposter info.yml issue.
=> Maintenance 03 11 2020

docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.install, scripts/cob_build_utilities.sh
Bid Amount install fix to sql statement and update to cob_build_utilities
issue #1120
=> Memory Limit and procurement sql fix

config/default/views.view.site_alerts.yml, docroot/modules/custom/bos_content/modules/node_landing_page/node_landing_page.module, docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module, docroot/modules/custom/bos_core/bos_core.module, docroot/themes/custom/bos_theme/templates/layout/page.html.twig, scripts/local/pull.sh, scripts/local/sync.sh
=> Coronavirus issues 1 du

composer.lock, scripts/deploy/travis_build.sh
=> Maintenance updates incl drupal 8.8.4.

config/default/views.view.bids_rfps.yml
=> Procurement issues 1274 and issue 1296

docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--bids-rfps.html.twig
=> Procurement issue 1296

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Reset  button moving below the filters
=> Procurement Filters Reset button style

config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices.html.twig
=> Recurring events 1308

config/default/views.view.events_and_notices.yml
Shakespeare is trembling somewhere.
=> Made spelling of cancelled US-correct.

config/default/views.view.events_and_notices.yml
=> Fixes cancelled logic for when not cancelled (!).

docroot/modules/custom/bos_components/modules/bos_emergency_alerts/js/bos_signup_emergency_alerts.js, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EverbridgeSubscriber.php
- Improved error response handling.
=> Updated new Object declaration.

config/default/core.entity_view_display.media.image.departmenticon_incirclelarge.yml, config/default/core.entity_view_display.paragraph.bos_signup_emergency_alerts.default.yml, config/default/core.entity_view_display.paragraph.card.default.yml, config/default/core.entity_view_display.paragraph.sidebar_item.default.yml, config/default/core.entity_view_display.paragraph.sidebar_item_w_icon.default.yml, config/default/core.entity_view_mode.media.departmenticon_incirclelarge.yml, docroot/modules/custom/bos_components/modules/bos_card/templates/paragraph--card.html.twig, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/templates/paragraph--bos-signup-emergency-alerts.html.twig, docroot/modules/custom/bos_components/modules/bos_sidebar/templates/paragraph--sidebar-item.html.twig, docroot/modules/custom/bos_content/modules/node_event/templates/field--node--field-event-type--event.html.twig, docroot/modules/custom/bos_vocab/modules/vocab_contact/templates/field--field-address.html.twig, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/templates/content/media--icon--departmenticon-incirclelarge.html.twig
=> Maintenance 04 29

docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/templates/content/media--icon--departmenticon-incirclelarge.html.twig
removes xml from svg before rendering, and properly sets blue theme.
=> Fixes icon when contains xml and on blue background.

composer.lock, docroot/themes/custom/bos_theme/bos_theme.theme
Updates applied:
- Updating symfony/yaml (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/translation (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/validator (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/serializer (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/routing (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/http-foundation (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/process (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/event-dispatcher (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/debug (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/http-kernel (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/dependency-injection (v3.4.39 => v3.4.40): Loading from …
=> Updates various contributed modules

.lando.yml, docroot/themes/custom/bos_theme/bos_theme.libraries.yml, scripts/local/lando-build-patterns.sh, scripts/local/lando-patterns-post-start.sh
makes pattern container available on patterns.lndo.site.
=> Updates patterns

docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
=> Translate Disclaimer

.travis.yml, docroot/modules/custom/bos_components/modules/bos_translate/bos_translate.libraries.yml, scripts/.config.yml, scripts/phing/phing-boston.yml
=> Code review changes.

composer.lock
=> Applies updates.

composer.lock
=> Maintenance updates including drupal core 8.8.6.

composer.lock
=> Maintenance 06-03-2020.

docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices.html.twig, docroot/modules/custom/bos_components/modules/bos_featured_topics/templates/field--component--field-title.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/field--component--field-component-title.html.twig, docroot/modules/custom/bos_components/modules/bos_list/templates/field--field-component-title--video--mode--full.html.twig, docroot/modules/custom/bos_components/modules/bos_news_and_announcements/templates/views-view-fields--news-and-announcements.html.twig, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/field--field-intro-text.html.twig, docroot/modules/custom/bos_content/modules/node_program_initiative_profile/templates/node--program-initiative-profile.html.twig, docroot/modules/custom/bos_content/modules/node_public_notice/templates/node--public-notice.html.twig, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/templates/layout/html.html.twig, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
=> Accessibility ticket #110

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/layout/region--footer.html.twig, docroot/themes/custom/bos_theme/templates/menu/menu--menu-footer-menu.html.twig
=> Accessibility tickets 108

composer.lock
=> Maintenance Drupal 8.9 Again.

composer.json, composer.lock
=> Maintenance 2020 06 24

docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
Metrolist having translation issues. Remove translate for now until solution is in place.
=> Fix metrolist notranslate issies

config/default/webform.webform.metrolist_launch_feedback.yml, config/default/webform.webform.metrolist_listing.yml
Update to MetroList WebForms: Adding emails and changing copy.
=> Metrolist dev

docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/index.html, docroot/modules/custom/bos_components/modules/bos_web_app/templates/paragraph--web-app.html.twig
Webapp translation temporary fix.
=> Metrolist notranslate

config/default/recaptcha_v3.settings.yml
Adding recaptcha_settings to config/default folder
=> Updated Recapture settings file

.travis.yml, docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
=> Translate issue 

composer.json, composer.lock, config/default/core.extension.yml
=> Updates drupal 8.9.1 to 8.9.2 plus views filters.

composer.json, composer.lock
Adds a js file to the libraries folders for BEF update.
=> Adds touch_punch js extension for mobile devices.

composer.lock
Maintenance updates:
-[ ] symfony/polyfill-iconv (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-ctype (v1.18.0 => v1.18.1)
-[ ] twig/twig (v1.43.0 => v1.43.1)
-[ ] symfony/polyfill-php72 (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-php70 (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-intl-normalizer (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-intl-idn (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-mbstring (v1.18.0 => v1.18.1)
-[ ] egulias/email-validator (2.1.18 => 2.1.19)
-[ ] symfony/polyfill-php80 (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-util (v1.18.0 => v1.18.1)
-[ ] symfony/polyfill-php56 (v1.18.0 => v1.18.1)
-[ ] squizlabs/php_codesniffer (3.5.5 => 3.5.6)
-[ ] doctrine/annotations (1.10.3 => 1.10.4)
-[ ] doctrine/event-manager (1.1.0 => 1.1.1)
-[ ] doctrine/persistence (1.3.7 => 1.3.8)
-[ ] …
=> Module updates incl corer 8.9.3.

composer.lock
=> Updates modules and core to 8.9.5.

.travis.yml, composer.json, composer.lock, config/default/metatag.metatag_defaults.front.yml, config/default/metatag.metatag_defaults.global.yml
=> Maintenance 2020 9 24 - csecurity update to 8.9.6

composer.lock
=> Maintenance updates including core update 8.9.7.

config/default/webform.webform.metrolist_listing_entry_form.yml, docroot/modules/custom/bos_components/modules/bos_newsletter/templates/paragraph--newsletter--sidebar.html.twig
Plumbs in the new contactform endpoint.
=> Contactform replacement

docroot/modules/custom/bos_components/modules/bos_iframe/bos_iframe.module, docroot/modules/custom/bos_components/modules/bos_iframe/templates/paragraph--iframe.html.twig, docroot/themes/custom/bos_theme/dist/js/all.js
iFrame component not working on the site #1641
Temporary removed resizer.js from pages until a proper tested fix is in.
=> Iframe bug fix.

composer.lock
=> Maintenance 2020-11-18 Core to 8.9.9.

docroot/modules/custom/bos_components/modules/bos_email/bos_email.routing.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/UpakneeAPI.php, scripts/deploy/travis_build.sh
Enables legacy endpoints from deprecated contactform nodejs webapp.
=> Contactform quickfixes

.lando.yml, scripts/cob_build_utilities.sh
Updates cloning methodology for patterns so that it can be sync'd with remote.
removes memory alloc which seems not to be very compatible with macs.
=> Updates cloning and removes container mem for Macs.

composer.lock
=> Updates to Drupal incl core->8.9.12

composer.lock
=> Maintenance updates incl core -> 8.9.13 (security)

config/default/config_ignore.settings.yml, config/default/salesforce.settings.yml, config/default/views.view.bhmaps.yml, config/default/views.view.entity_reference_filters.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/views_bh_listings.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-meeting-notice.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-meeting.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-read-more-text.html.twig
* Config updates  for BH from PRD
* Style fixes for BH Maps header and footer
* BH Read More Feature and other meeting features/fixes
* adding in ignore for SF
=> [DEPLOY TO STAGE] Building Housing: Configs from PRD, updates to styles, meeting updates, read-more feature.  

config/default/config_ignore.settings.yml, config/default/salesforce.settings.yml, config/default/views.view.bhmaps.yml, config/default/views.view.entity_reference_filters.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/views_bh_listings.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-meeting-notice.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-meeting.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-read-more-text.html.twig
[DEPLOY TO STAGE] MetroList: Fix for listing form error
=> [DEPLOY TO STAGE] MetroList: Fix for listing form error

config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--large-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--medium-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-auto.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-large.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-medium.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-small.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> events ui update 2

README.md, composer.lock
=> Maintenance updates.

config/default/bos_city_score.settings.yml, config/default/bos_mnl.settings.yml, config/default/config_ignore.settings.yml
Alters settings files so that bos_core settings are not overridden during deploy.
=> Protect manifest settings

docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module
#2009 - "revision" links are broken: add in check if $node is not a string.
=> #2009 - "revision" links are broken

docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module, scripts/deploy/travis_deploy.sh
[RELEASE TO STAGE] #2009 - "revision" links are broken
=> [RELEASE TO STAGE] #2009 - "revision" links are broken

docroot/themes/custom/bos_theme/dist/js/all.js, docroot/themes/custom/bos_theme/templates/layout/_____page.html.twig, docroot/themes/custom/bos_theme/templates/layout/html.html.twig, docroot/themes/custom/bos_theme/templates/layout/page.html.twig, docroot/themes/custom/bos_theme/templates/layout/region--footer.html.twig
Issues https://github.com/CityOfBoston/Iterators/issues/124
https://github.com/CityOfBoston/Iterators/issues/207
=> Issues 124, 207

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
* Updated validation.
* Latest from Develop.
=> [RELEASE TO STAGE] Updated contactform validation

config/default/core.extension.yml, config/default/filter.format.filtered_html.yml, config/default/filter.format.full_html.yml, docroot/modules/custom/bos_text_editor/bos_text_editor.info.yml, docroot/modules/custom/bos_text_editor/bos_text_editor.module, docroot/modules/custom/bos_text_editor/src/Plugin/Filter/FilterBosTextEditorTables.php
WYSIWYG: Ability to make tables responsive
=> Feature/#646 - Responsive table fix

composer.lock
=> Maintenance updates incl core -> 8.9.14 (security)

docroot/modules/custom/bos_components/modules/bos_list/templates/views-exposed-form--topic-landing-page.html.twig, docroot/themes/custom/bos_theme/dist/js/all.js
https://github.com/CityOfBoston/Iterators/issues/124
=> Issue https://github.com/CityOfBoston/Iterators/issues/124

config/default/views.view.rss_feeds.yml
=> #2028 - Fixes for RSS feeds

docroot/modules/custom/bos_content/modules/node_person_profile/templates/node--person-profile--embed.html.twig, docroot/modules/custom/bos_content/modules/node_person_profile/templates/node--person-profile--listing.html.twig, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/templates/node--person-profile--department-listing.html.twig
https://github.com/CityOfBoston/Iterators/issues/135
=> https://github.com/CityOfBoston/Iterators/issues/135

scripts/deploy/cob_utilities.sh
Minimize the DB size on non-prod environments.
=> Adds drush commands to empty queues and prune salesforce.

composer.lock, scripts/deploy/travis_deploy.sh
=> Maintenance update

README.md
Small change to get longer timeouts included from private repo changes.  
This [commit](https://github.com/CityOfBoston/boston.gov-d8-private/commit/7fbd42e12d25248b77110d2759fa62d33fe1ea1e)
=> Samll change to initiate build.

composer.lock
=> Maintenance updates - security core to 8.9.16.

config/default/webform.webform.building_housing_feedback.yml, config/default/webform.webform.metrolist_launch_feedback.yml
Update DND webforms with new emails and email field on feedback form
=> feature/#2111 - Update DND webforms with new emails and email field

docroot/modules/custom/bos_components/modules/bos_card/bos_card.module
Remove old method of getting card background image from thumbnail file (was setup to use media later in the code)
=> #2116 - Clarification around image error on live site

docroot/modules/custom/bos_core/bos_core.install
Increase performance of views using date_recur, add index to the DB table
=> #2120 - Increase performance of views using date_recur, add index

docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--referenced-large-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--referenced-medium-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--related-attachment-large.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--related-attachment-medium.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--related-large.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--related-medium.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-large-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-large.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-medium-attachment.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-medium.html.twig, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices.html.twig
Merge into a combined release branch to save credits with Travis.
=> #2135 "Canceled" meetings causing bug in event component

composer.json, composer.lock
Gathering patches for root package.
=> [DEPLOY TO STAGE] Maintenance and IDP.

config/default/views.view.bhmaps.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/views_bh_listings.css
Feature/#2020 - Realign the search bar so it's left aligned
=> Feature/#2020 - Realign the search bar so it's left aligned

composer.lock
Deploys maintenance updates incl core to 8.9.18
=> [DEPLOY TO STAGE]

composer.json
Oops, pushed the composer.lock file directly to develop, so this is just a small change to prompt a deploy.
The composer update that will occur during this commit is:
=> Updates core to 8.9.19

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, scripts/.config.yml
removed reference to local url
=> Config.yml file update. Css override bug fix

docroot/modules/custom/bos_components/modules/bos_link_collections/templates/paragraph--group-of-links-list.html.twig, docroot/modules/custom/bos_content/modules/node_how_to/templates/paragraph--daily-hours.html.twig
=> All side templated bug fixes

docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module, docroot/modules/custom/bos_components/modules/bos_events_and_notices/templates/views-view-fields--events-and-notices--upcoming-large.html.twig, docroot/modules/custom/bos_content/modules/node_event/node_event.module, docroot/modules/custom/bos_content/modules/node_event/templates/node--event--featured-item.html.twig, docroot/modules/custom/bos_content/modules/node_post/templates/node--post--listing.html.twig
Phone format added for node_event and bos_events_and_notices
=> Events - Featured events and

docroot/modules/custom/bos_content/modules/node_post/node_post.module, docroot/modules/custom/bos_content/modules/node_post/templates/node--post--featured-item.html.twig, docroot/modules/custom/bos_content/modules/node_post/templates/node--post--listing.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
News and announcements bug fix
=> Patterns cob theme

docroot/modules/custom/bos_components/modules/bos_list/templates/views-view--topic-landing-page.html.twig, docroot/modules/custom/bos_components/modules/bos_text/bos_text.module, docroot/modules/custom/bos_content/modules/node_topic_page/templates/node--topic-page.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> Bug fixes!

composer.lock
composer.lock for maintenance - security updates.
=> Security update for drupal + contrib modules.

config/default/core.extension.yml, docroot/modules/custom/bos_components/modules/bos_bibblio/bos_bibblio.libraries.yml, docroot/modules/custom/bos_components/modules/bos_bibblio/bos_bibblio.module, docroot/modules/custom/bos_components/modules/bos_bibblio/js/bibblio-custom.js
- Added custom Bibbblio id as Drupal node id.
=> - Added new catalogue prepping for new content items.

docroot/modules/custom/bos_content/modules/node_site_alert/templates/node--site-alert.html.twig, docroot/themes/custom/bos_admin/css/tabs.css
#2398 
#2382 (via patterns update)
=> Hotfix: Fixes site alert non-dsplay issue (D9).

docroot/themes/custom/bos_admin/bos_admin.theme, docroot/themes/custom/bos_admin/css/bos_admin.css, docroot/themes/custom/bos_admin/css/tabs.css
Fixes Content Author cannot edit draft after D9 Update
also, 
#2398 Drag arrow vertically centered
#2399 Call to Action Buttons are Grey
=> Fixes minor backend issues - hotfix

docroot/modules/custom/bos_swiftype/bos_swiftype.module, docroot/modules/custom/bos_swiftype/src/Controller/SwiftypeController.php, docroot/modules/custom/bos_swiftype/templates/search-results.html.twig
=> Fixes swifttype for d9

composer.lock, docroot/modules/custom/bos_components/modules/bos_mnl/composer.json, docroot/modules/custom/bos_components/modules/bos_mnl/drush.services.yml, docroot/modules/custom/bos_components/modules/bos_mnl/src/Commands/MnlDrushCommands.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Controller/MnlUtilities.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Form/MNLSettingsForm.php
- behat/mink (v1.9.0 => v1.10.0)
- behat/mink-selenium2-driver (v1.5.0 => v1.6.0)
- behat/transliterator (v1.3.0 => v1.5.0)
- drupal/core (9.3.8 => 9.3.9)
- drupal/core-composer-scaffold (9.3.8 => 9.3.9)
- drupal/dropzonejs (2.5.0 => 2.6.0)
- drupal/google_tag (1.4.0 => 1.5.0)
- drupal/media_entity_instagram (3.0.6 => 3.0.7)
- drupal/menu_block (1.7.0 => 1.8.0)
- drupal/moderation_sidebar (1.4.0 => 1.5.0)
- drupal/office_hours (1.5.0 => 1.6.0)
- drupal/views_bulk_operations (4.1.0 => 4.1.2)
- firebase/php-jwt (v6.0.0 => v6.1.0)
- guzzlehttp/psr7 (1.8.3 => 1.8.5)
- instaclick/php-webdriver (1.4.10 => 1.4.11)
- laminas/laminas-diactoros (2.8.0 => 2.9.0)
- laminas/laminas-feed (2.16.0 => 2.17.0)
- mglaman/phpstan-drupal (1.1.13 => 1.1.14)
- phpdocumentor/type-resolver (1.6.0 => 1.6.1)
- …
=> Maintenance 03 30 2022

docroot/modules/custom/bos_components/modules/bos_messages/src/Plugin/Field/FieldWidget/MODRecurWidget.php, scripts/.config.yml
Dev pull and private repo branch switch - config.yml
=> Points app ci

composer.lock
=> Maintenance incl core 9.3.12

docroot/modules/custom/bos_components/modules/bos_web_app/bos_web_app.libraries.yml
=> Updates js versions to prompt re-cache (hotfix)

composer.json, composer.lock
Fixes issue where content_authors and content_editors cannot edit paragraphs on entities.  #2519
=> Fixes content author issue #2519.

config/default/config_split.config_split.acquia_dev.yml
=> Fix to config_split! (hotfix)

config/default/core.base_field_override.node.person_profile.title.yml
https://bostondoit.atlassian.net/browse/DIG-19?atlOrigin=eyJpIjoiNTJjNWEzODM2MjMzNGNiZWE2M2VmYzY0ZGVlZjljYzUiLCJwIjoiaiJ9
=> Change field in "person profile" content type

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
https://bostondoit.atlassian.net/jira/software/c/projects/DIG/boards/4?modal=detail&selectedIssue=DIG-20
=> Make CSS consistent / the same on back-end and front-end

composer.lock
=> Security update core to 9.3.16

composer.lock, config/default/config_split.config_split.acquia_dev.yml
=> [DEPLOY TO STAGE] Core 9.3.16

composer.lock
- Downgrading drush/drush (10.6.2 => 10.6.1)
- Downgrading symfony/http-foundation (v4.4.42 => v4.4.41)
=> JIRA: DIG-139: Maintenance

config/default/core.entity_view_display.node.public_notice.featured_item.yml, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
https://bostondoit.atlassian.net/jira/software/c/projects/DIG/boards/4?modal=detail&selectedIssue=DIG-28
=> Public notices featured

config/acquia_dev/purge.plugins.yml, config/acquia_prod/purge.plugins.yml, config/acquia_stage/purge.plugins.yml
=> hotfix: add purger to config_split across environments

config/acquia_dev/purge.plugins.yml, config/acquia_prod/purge.plugins.yml, config/acquia_stage/purge.plugins.yml
=> hotfix: fixes config yml format (string)

config/default/core.entity_view_display.media.document.default.yml, config/default/core.entity_view_display.media.document.thumbnail.yml, config/default/core.entity_view_display.media.icon.default.yml, config/default/core.entity_view_display.media.icon.thumbnail.yml, config/default/core.entity_view_display.media.image.default.yml, config/default/core.entity_view_display.media.image.departmenticon_incirclelarge.yml, config/default/core.entity_view_display.media.image.embedded.yml, config/default/core.entity_view_display.media.image.thumbnail.yml, config/default/core.entity_view_display.node.bh_update.default.yml, config/default/core.entity_view_display.node.department_profile.icon_popup.yml, config/default/core.entity_view_display.node.department_profile.listing.yml, config/default/core.entity_view_display.paragraph.quote.default.yml, config/default/core.entity_view_display.paragraph.transactions.group_of_links.yml, config/default/core.entity_view_display.user.user.compact.yml, config/default/views.view.events_and_notices.yml, config/default/views.view.media.yml, config/default/views.view.media_cob.yml, config/default/views.view.media_entity_browser.yml, config/default/views.view.related_events.yml, config/default/views.view.status_items.yml, config/default/views.view.wysiwyg_entity_browser.yml
Alters config after update so the config import completes.
=> hotfix: fixes config for lazy update

config/default/field.storage.paragraph.field_social_icon.yml, docroot/modules/custom/bos_components/config/install/field.storage.paragraph.field_social_icon.yml
https://bostondoit.atlassian.net/jira/software/c/projects/DIG/boards/4?modal=detail&selectedIssue=DIG-43
=> Social Icons update

config/default/views.view.status_items.yml, docroot/themes/custom/bos_admin/bos_admin.theme, docroot/themes/custom/bos_admin/css/bos_admin.css, docroot/themes/custom/bos_theme/bos_theme.theme
Various updates for multilanguage support.
=> DIG-416, DIG-418, DIG-417, DIG-399

composer.lock
=> DIG-471 - Maintenance Updates

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php
Better fix for 431 whch does not regress other issues
=> Hotfix DIG-431

docroot/modules/custom/bos_content/modules/node_emergency_alert/node_emergency_alert.module, docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
https://bostondoit.atlassian.net/jira/software/c/projects/DIG/boards/4?modal=detail&selectedIssue=DIG-450&assignee=62a0d5b66a7b750068a2f2ec
=> Sample page and fix to page headers on Drupal admin and nodes

composer.lock
- Upgrading drupal/admin_toolbar (3.1.0 => 3.1.1)
- Upgrading drupal/captcha (1.3.0 => 1.4.0)
- **Upgrading drupal/core (9.4.2 => 9.4.3)**
- Upgrading drupal/core-composer-scaffold (9.4.2 => 9.4.3)
- Upgrading drupal/ctools (3.8.0 => 3.9.0)
- Upgrading drupal/entity_browser (2.7.0 => 2.8.0)
- Upgrading drupal/entity_browser_entity_form (2.7.0 => 2.8.0)
- Upgrading drupal/environment_indicator (4.0.6 => 4.0.7)
- Upgrading drupal/xmlsitemap (1.2.0 => 1.3.0)
- Upgrading laminas/laminas-servicemanager (3.15.1 => 3.16.0)
- Upgrading laminas/laminas-stdlib (3.10.1 => 3.11.0)
- Upgrading sirbrillig/phpcs-variable-analysis (v2.11.3 => v2.11.4)
=> DIG-528 Maintenance Updates incl core to 9.4.3 (security update)

composer.lock
- Upgrading doctrine/event-manager (1.1.1 => 1.1.2)
**- Upgrading drupal/core (9.4.3 => 9.4.4)**
- Upgrading drupal/core-composer-scaffold (9.4.3 => 9.4.4)
- Locking drupal/core-utility (9.4.4)
- Upgrading drupal/ctools (3.9.0 => 3.10.0)
- Upgrading drupal/jsonapi_extras (3.20.0 => 3.21.0)
- Upgrading drupal/pathauto (1.10.0 => 1.11.0)
- Upgrading drupal/restui (1.20.0 => 1.21.0)
- Upgrading drupal/token (1.10.0 => 1.11.0)
- Upgrading gettext/gettext (4.x-dev 3e7460f => 4.x-dev 3f7bc5e)
- Upgrading laminas/laminas-diactoros (2.13.0 => 2.14.0)
- Upgrading psy/psysh (v0.11.7 => v0.11.8)
- Upgrading symfony/browser-kit (v4.4.37 => v4.4.44)
- Upgrading symfony/cache (v5.4.10 => v5.4.11)
- Upgrading symfony/config (v4.4.42 => v4.4.44)
- Upgrading symfony/console (v4.4.43 => v4.4.44)
- …
=> DIG-621 Drupal 9 Minor release update (9.4.4)

config/default/core.entity_view_display.node.post.listing.yml, docroot/modules/custom/bos_content/modules/node_post/templates/node--post--listing.html.twig
=> DIG-26 - News listing page

config/default/pathauto.pattern.building_housing_project.yml, config/default/pathauto.pattern.default_event_path.yml, config/default/pathauto.pattern.department_profile_pattern.yml, config/default/pathauto.pattern.metrolist_listing.yml, config/default/pathauto.pattern.my_neighborhood_lookup_so_can_disable_cache_in_ape_.yml, config/default/pathauto.pattern.pathauto_node_pattern.yml, config/default/pathauto.pattern.place_profile_path.yml, config/default/pathauto.pattern.post_path.yml, config/default/pathauto.pattern.procurement_advertisement_path.yml, config/default/pathauto.pattern.program_initiative_profile_path.yml, config/default/pathauto.pattern.public_notice_path.yml
fixes path_auto yml's as per:
https://www.drupal.org/project/ctools/issues/3300682
=> Updates 'id:node_type' to 'id:entity_bundle:node' in pathauto*.ymls

docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessImport.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessUpdate.php, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
Addresses runtime issue on prod.
Updates webform UX for content editors (watermark).
=> Hotfix: Dig 437 mnl sync

docroot/modules/custom/bos_components/modules/bos_mnl/src/Controller/MnlUtilities.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessImport.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessUpdate.php
Hotfix so we dont get too many backups etc on environments.
=> Hotfix: Traps errors and reports so we can see what's going on.

docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
DIG-438 Contact validation test
=> DIG-438 Contact validation test

docroot/modules/custom/bos_vocab/modules/vocab_features/templates/taxonomy-term--features--sidebar-right.html.twig, docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
DIG-438 and DIG-733 Contact validation test and Features sidebar svg bg fix
=> DIG-438 and DIG-733

docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
DIG-438 Contact validation test bug fix
=> DIG-438 Contact validation test bug fix

config/default/webform.webform.metrolist_listing.yml, config/default/webform.webform.metrolist_listing_entry_form.yml, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/misc/status-messages.html.twig
=> [develop] Language updates to metrolist listing form.

composer.lock
=> [develop] Maintenance Updates incl core 9.4.4

docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-developer-info.html.twig
=> [develop] Fixes layout on BH Project

docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.libraries.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.module, docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_block_avaliable_units.css, docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_feedback.css
=> (develop) Hotfix for metrolist feedback styling

composer.lock, config/default/webform.webform.metrolist_listing.yml, config/default/webform.webform.metrolist_listing_entry_form.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.libraries.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.module, docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_block_avaliable_units.css, docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_feedback.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-developer-info.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/misc/status-messages.html.twig
DIG-381: Metrolist confirmation text changes
DIG-741: Maintenance update
DIG-744: Metrolist Sidebar fix
DIG-746: Metrolist feedback styling
=> (production) Maintenance and some metrolist updates

docroot/modules/custom/bos_content/modules/node_listing_page/node_listing_page.module, docroot/modules/custom/bos_content/modules/node_listing_page/templates/node--listing-page.html.twig
DIG-319 Structure alignment with Patterns
=> DIG-319 Structure alignment with Patterns

config/default/views.view.metrolist.yml
=> (develop) Fixes to dates and links on metrolist search page

config/default/views.view.metrolist.yml
=> (develop) Changes units created date to a MAX aggregation to avoid dups.  hotfix

config/default/views.view.metrolist.yml
=> (stage) Metrolist search fix. hotfix

config/default/core.entity_view_display.node.bh_meeting.default.yml, config/default/salesforce_mapping.salesforce_mapping.bh_community_meeting_event.yml, config/default/views.view.metrolist.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php
Dig-542 Calendar events do not show physical location
=> (develop) Improve building housing meeting address and virtual meeting

config/default/views.view.metrolist.yml
DIG-809 Issues accessing Metrolist from external devices
=> (develop) Metrolist search not working on IoS.

docroot/modules/custom/bos_content/modules/node_status_item/src/Plugin/views/style/Bos311Serializer.php
DIG-824: Update BOS311 API for Chinese translation
=> (develop) Creates zh-hant and zh translations

config/default/webform.webform.metrolist_listing.yml, config/default/webform.webform.metrolist_listing_entry_form.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/EmailControllerBase.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/EmailTemplateCss.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetroListInitiationForm.php
=> (stage) Stop re-submission of metrolist form once submitted

config/default/webform.webform.metrolist_listing_entry_form.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php
=> (develop) refactors email handlers

config/default/webform.webform.metrolist_listing.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php, docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
=> (develop) Update admin email alert (metrolist listing form)

config/default/webform.webform.metrolist_listing.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php, docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
=> (develop) Fixes form submission when records updated.  

docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php
=> (develop) Adds link to MOH notification email

.github/percy/snapshot_config.yml, .github/workflows/percy_snapshot.yml
Add the github actions and percy.cli yml files in for percy testing
=> Adds yml files for percy via a github action. DIG-853

.github/percy/snapshot_config.yml, .github/workflows/percy_snapshot.yml
FINAL.
(Until page-review is completed)
=> Enables full list of frontend pages. DIG-853

.travis.yml, scripts/.config.yml
DIG-876 Internal Link Exception error
=> DIG-876 Internal Link Exception error

.github/percy/snapshot_config.yml, .github/percy/snapshot_interactive_config.js, .github/workflows/percy_snapshot_interactive.yml
=> (develop) refined list of pages to scan.

docroot/modules/custom/bos_core/bos_core.module
DIG-876 - Re-enables content authors to add aliases and `node/nid` style internal links
=> (develop) Improved internal link support 

docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module
DIG-876.
Fix to specific error on link_collections with new internal link treatment.
=> (develop) Fix to internal link issue for link_collections. 

docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php
DIG-925 - makes a nicer sentence for email comms back to submitter,
=> (develop) Email language errors

docroot/themes/custom/bos_theme/bos_theme.theme
DIG-67
Refactors breadcrumb code, aslo extends the breadcrumb detection to find redirected paths as well as aliased paths.
=> (develop) Enables redirects to appear in breadcrumb. 

config/default/webform.webform.metrolist_listing.yml
=> (develop) Clarify "Minimum income" is annual income

.github/percy/snapshot_config.yml
Updated the list of pages to be scanned as per James' list.
=> DIG-949 Verify pages to be scanned by percy - hotfix

.github/percy/snapshot_config.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_content/modules/node_post/templates/node--post.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> (stage) Second reference for contact form issue, publish date on posts

docroot/modules/custom/bos_content/modules/node_post/templates/node--post.html.twig
DIG-872 Published date text added
=> DIG-872 Published date text added

docroot/themes/custom/bos_theme/bos_theme.theme
=> (develop) Some legacy breadcrumbs thow error - hotfix.

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php
=> (stage) legacy links in breadcrumb, published on for posts - hotfix

README.md
=> Kick a redeploy

composer.json, composer.lock, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php
=> (develop) Scheduled Drupal updates

.github/percy/snapshot_config_stage.yml, .github/workflows/percy_snapshot_static_stage.yml
[DIG-853](https://bostondoit.atlassian.net/browse/DIG-853) - Adds cut-down Percy test on commit to production branch.
=> (develop) Adds cut-down Percy test on commit to production branch.

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php
=> (develop)- Fix reply to address in contact form.

docroot/modules/custom/bos_components/modules/bos_web_app/bos_web_app.libraries.yml
DIG-881 My Neighborhood - Switching Summer and Winter cards;
=> (develop) My Neighborhood - Switching Summer and Winter cards - hotfix

README.md, composer.lock
=> [develop] updates drupal to 9.4.8, DIG-1206

docroot/sites/default/settings.php
DIG-1206.
Tests to see if the database class pre-loader works on Acquia settings file. If it does then we can upgrade core to 9.4.8.
=> (develop) Adds (mysql) class preloader to settings file. 

scripts/deploy/hook_manual.sh
=> (develop) Adds script to sync environment from local machine if update fails.

docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-area-results--election-card.html.twig, docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-contest-results--election-card.html.twig, docroot/modules/custom/bos_content/modules/node_elections/templates/taxonomy-term--election-contests.html.twig
DIG-1093 Unofficial election results
=> DIG-1093 Unofficial election results

.travis.yml, scripts/.config.yml
=> DIG-1299 Create config files for CI environment.

docroot/modules/custom/bos_content/modules/node_elections/src/Controller/ElectionFileUploader.php, docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_Apr_2022_01.xml, docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_Nov_2021_01.xml, docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_Nov_2021_02.xml, docroot/modules/custom/bos_content/modules/node_elections/tmp/Contest_Overview_Data_Nov_2021_03.xml
=> First-time run fixes, improved sorting & extra import files 

config/default/core.entity_view_display.node.election_report.default.yml, docroot/modules/custom/bos_content/modules/node_elections/node_elections.module
=> Switches node to election_card display, add columns on taxonomy listing

docroot/modules/custom/bos_content/modules/node_elections/src/Controller/ElectionFileUploader.php, docroot/modules/custom/bos_core/src/Commands/BosCoreCommands.php
Also fixes the error shown on `drush bcss`.
=> (develop) makes party uppercase for state primaries Dig-1333

docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--election-card.html.twig
=> DIG-1363 Disclaimer text

docroot/modules/custom/bos_content/modules/node_elections/src/Form/ElectionUploaderForm.php, docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--election-card.html.twig, docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--full.html.twig
DIG-1374 Add error validation in election uploads
=> DIG-1374 Add error validation in election uploads

config/default/core.entity_view_display.node.election_report.election_card.yml
DIG-1374 Report Updated date field not in EST
=> DIG-1374 Report Updated date field not in EST

config/default/core.entity_form_display.paragraph.quote.default.yml
DIG-878 'Grid of quotes' component image upload issues
=> DIG-878 'Grid of quotes' component image upload issues

config/default/core.entity_form_display.node.election_report.default.yml, config/default/core.entity_view_display.node.election_report.election_card.yml, config/default/core.entity_view_display.node.election_report.teaser.yml, config/default/field.field.node.election_report.field_election_disclaimer.yml, config/default/field.storage.node.field_election_disclaimer.yml, config/default/node_elections.settings.yml, docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--election-card.html.twig, docroot/modules/custom/bos_content/modules/node_elections/templates/node--election-report--full.html.twig
DIG-1393 Add field to Drupal to allow election editors / admins to edit disclaimer
=> DIG-1393 Add field to Drupal for disclaimer

docroot/modules/custom/bos_content/modules/node_elections/src/Form/ElectionUploaderForm.php
=> [Develop] Error on elections file upload crashes upload form

composer.json, composer.lock
Removes out-dated patch for drupal/console.
Adds patch for Masquerade issue with SimpleSAML.
Routine maintenance:
=> (develop) Drupal Maintenance DIG-1511 

config/default/block.block.webform_2.yml, config/default/webform.webform.website_feedback_form.yml, config/default/webform.webform_options.feedback_form.yml, config/default/webform.webform_options.yes_no.yml, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> DIG-1463 Feedback form

docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.module
These tickets were closely related with underlying problem causing different issues
=> DIG-1544 & DIG-1452 Updates attribute object.

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/dist/js/all.js
=> DIG-1307 mobile tables update

config/default/core.entity_form_display.paragraph.cabinet.default.yml, config/default/core.entity_form_display.paragraph.text.default.yml
DIG-883 Add theme selection to drupal admin
=> DIG-883 Add theme selection to drupal admin

docroot/modules/custom/bos_components/modules/bos_quote/templates/paragraph--quote.html.twig
DIG-1653 Grid of quotes last name bug
=> DIG-1653 Grid of quotes last name bug

composer.json, patches/addtocal_dig-1687.patch
DIG-1687 'Add to calendar' button not working on 'events'
=> DIG-1687 'Add to calendar' button not working on 'events'

config/default/views.view.metrolist.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_block_avaliable_units.css
DIG-1584[ Change text on metrolist unit details](https://bostondoit.atlassian.net/browse/DIG-1584)
=> (develop)  Changes Calculate to Estimate on listing DIG-1584

docroot/modules/custom/bos_content/modules/bos_metrolist/css/views_ml_block_avaliable_units.css
DIG-1561 - [Cards styling](https://bostondoit.atlassian.net/browse/DIG-1561)
=> (develop) DIG-1561 fixed css for story cards

patches/addtocal_dig-1687.patch
DIG-1687 Updates patch to force rebuild and to apply to correct file
=> (stage) Hotfix DIG-1687

docroot/modules/custom/bos_components/css/component-theme.css, docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module, docroot/modules/custom/bos_components/modules/bos_link_collections/templates/paragraph--group-of-links-mini-grid.html.twig
DIG-883 Add ability to choose theming for select components
=> DIG-883 Add ability to choose theming for select components

docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Pdf.php, docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Pdf2.php, docroot/modules/custom/bos_components/modules/bos_pdfmanager/src/Controller/Fpdf.php, docroot/modules/custom/bos_components/modules/bos_pdfmanager/src/Controller/PdfToolkit.php
DIG-1720 [PDF Generation may fail if multiple requests occur simultaneously](https://bostondoit.atlassian.net/browse/DIG-1720)
- this actually is that lowercase url parts cause 404 error.
=> (develop) Hotfix simultaneous PDF requests and lowercase year

composer.lock
=> (develop) DIG-1722 Drupal Maintenance Updates

docroot/modules/custom/bos_components/modules/bos_link/bos_link.module
DIG-1679 Adjust style for document link button in "three column w/ image" component
=> DIG-1679 Adjust style for document link button

composer.json, composer.lock
This rollsback and locks the drupal/webform version to 1.6.3 in composer.
=> (develop) DIG-1770 (hotfix) Metrolist Listing Form Error

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/README.md
A clean deploy to stage to tidy up earlier deploy issues.
=> force deploy to stage (untracked)

.github/config/releaseNotesConfig.yml, .github/workflows/releaseNotes.yml, .lando.yml, RELEASE.md
Hotfix because the Acquia environment does not need updating.
=> (develop) (hotfix) Add Github Actions for release.

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php
=> (hotfix) Fixes runtime error in array parsing.

config/default/webform.webform.metrolist_listing.yml, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> (develop) DIG-1860 update to config changes (hotfix)

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php
NOT h*tfix so the last 4 PR merges are fully built on Acquia
=> (develop) DIG-1745 updated funding awarded msg

docroot/modules/custom/bos_components/modules/bos_translate/css/translate.css, docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
DIG-1756 Add rtl to selected translations
=> DIG-1756 Add rtl to selected translations

docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
DIG-1756 fix to Arabic translation
=> DIG-1756 fix to Arabic translation

.github/config/releaseNotesConfig.yml, config/default/block.block.ml_listing_entry.yml
DIG-1901 [Fix Metrolist listing form website](https://bostondoit.atlassian.net/browse/DIG-1901)
=> (develop) Updates block to appear on node as well as alias DIG-1901

composer.lock
DIG-1933 [Drupal Maintenance Updates](https://bostondoit.atlassian.net/browse/DIG-1933)
=> (Develop) Drupal core+contrib updates

docroot/modules/custom/bos_components/modules/bos_translate/bos_translate.info.yml, docroot/modules/custom/bos_components/modules/bos_translate/css/translate.css, docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
DIG-1756 [Add language titles in native language to Google translate](https://bostondoit.atlassian.net/browse/DIG-1756)
=> (develop) Add language titles in native language to Google translate DIG-1756

composer.json, composer.lock, config/default/core.extension.yml, config/default/lightning_core.versions.yml
DIG-1832 Add Rollbar to Drupal
=> (develop) DIG-1832 Add Rollbar to Drupal

.travis.yml, scripts/.config.yml
Trying to kick start travis...
=> Trying to kick start travis

.travis.yml, docroot/modules/custom/bos_linkit_extension/bos_linkit_extension.module, scripts/.config.yml
DIG-1937 Remove extra fields in "add link" advanced section of WYSIWYG editor
=> DIG-1937 Remove extra fields in "add link" advanced section of WYSIWYG editor

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> DIG-1718 Fixed .nv-m menu height

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php
DIG-1949 [Confirmation emails failing in marriage intention application.](https://bostondoit.atlassian.net/browse/DIG-1949)
=> (develop) (hotfix) Adds extra logging so can see the issue postmark. DIG-1949

RELEASE.md
DIG-1949 [Confirmation emails failing in marriage intention application.](https://bostondoit.atlassian.net/browse/DIG-1949)
=> (stage)  (hotfix) Adds extra logging so can see the issue postmark. DIG-1949

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Registry.php, scripts/deploy/cob_utilities.sh
DIG-1949 [Confirmation emails failing in marriage intention application.](https://bostondoit.atlassian.net/browse/DIG-1949)
=> (develop) (hotfix) Confirmation emails failing in marriage intention application DIG-1949

.travis.yml, config/default/bos_email.settings.yml, config/default/core.extension.yml, config/default/lightning_core.versions.yml, config/local/config_ignore.settings.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.module, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Plugin/QueueWorker/ContactformProcessItems.php
DIG-1949 [Confirmation emails failing in marriage intention application](https://bostondoit.atlassian.net/browse/DIG-1949)
=> (develop) Confirmation emails failing in marriage intention application DIG-1949

docroot/modules/custom/bos_linkit_extension/bos_linkit_extension.module
DIG-1937  Remove extra fields in "add link" advanced section of WYSIWYG editor
=> DIG-1937 Remove extra fields in "add link" advanced section of WYSIWY

config/default/bos_email.settings.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.module, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php, docroot/modules/custom/bos_components/modules/bos_email/src/EmailTemplateInterface.php, docroot/modules/custom/bos_components/modules/bos_email/src/Plugin/QueueWorker/ContactformProcessItems.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Registry.php
DIG-1899 [Investigate options for auto reply responses through Postmark](https://bostondoit.atlassian.net/browse/DIG-1899)
Also revisits
DIG-1975 [Add new Postmark channel for Metrolist](https://bostondoit.atlassian.net/browse/DIG-1975)
DIG-1949 [Confirmation emails failing in marriage intention application](https://bostondoit.atlassian.net/browse/DIG-1949)
DIG-160 [Address queue issues with Postmark and Drupal](https://bostondoit.atlassian.net/browse/DIG-160)
=> (develop) Investigate options for auto reply responses through Postmark DIG-1899

composer.lock, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php
DIG-1987 [Boston.gov Drupal Maintenance Updates](https://bostondoit.atlassian.net/browse/DIG-1987)
DIG-1899 [Investigate options for auto reply responses through Postmark](https://bostondoit.atlassian.net/browse/DIG-1899)
=> (develop) Boston.gov Drupal Maintenance Updates DIG-1987

docroot/modules/custom/bos_core/bos_core.module, docroot/themes/custom/bos_admin/bos_admin.theme
DIG-1924 [Display BPHC users in Drupal with actual names](https://bostondoit.atlassian.net/browse/DIG-1924)
=> (develop) (hotfix) Display BPHC users in Drupal with actual names DIG-1924

config/acquia_prod/config_ignore.settings.yml, config/default/bos_email.settings.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.module
Ensures that prod configs are not overwritten by accident.
=> (develop) (hotfix) Adds alerts when emails fail to send. DIG-160

docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php
Also enables html option for contactform.
=> DIG-1899 (hotfix) Auto-reply to contact form emails.

docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.menu.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.routing.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-document.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-text.html.twig
=> DIG 465 building housing dup atachment fix

docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
=> (develop) (hotfix) Handles missing suggested removal date DIG-2007

config/default/webform.webform.metrolist_listing.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
DIG-2007 [Reverts update from Nov 2022](https://bostondoit.atlassian.net/browse/DIG-2007)
=> (develop) (hotix) DIG-2007 Reverts update from Nov 2022

composer.lock
Upgrading drupal/acquia_connector (4.0.3 => 4.0.4)
Upgrading drupal/captcha (1.9.0 => 1.10.0)
Upgrading drupal/core (9.5.5 => 9.5.7)
Upgrading drupal/core-composer-scaffold (9.5.5 => 9.5.7)
Upgrading drupal/libraries (3.0.0-beta2 => 3.0.0-beta3)
Upgrading drupal/moderation_dashboard (1.3.0 => 1.4.0)
Upgrading drupal/office_hours (1.7.0 => 1.8.0)
Upgrading drupal/poll (1.5.0 => 1.6.0)
Upgrading drupal/recaptcha_v3 (1.7.0 => 1.8.0)
Upgrading drupal/salesforce (5.0.0 => 5.0.2)
Upgrading drupal/search_api (1.28.0 => 1.29.0)
Upgrading drupal/votingapi (3.0.0-beta3 => 3.0.0-beta4)
Upgrading drupal/workflow (1.6.0 => 1.7.0)
Upgrading phpdocumentor/type-resolver (1.7.0 => 1.7.1)
Upgrading phpstan/phpdoc-parser (1.15.3 => 1.17.1)
Upgrading phpstan/phpstan (1.10.7 => 1.10.11)
Upgrading …
=> (develop) Drupal Maintenance incl code 9.5.7 DIG-2036

.github/percy/snapshot_config.yml
DIG-1592 - [Additional sample pages for percy to check](https://bostondoit.atlassian.net/browse/DIG-1592)
=> (develop) Additional pages for percy to check 

config/default/views.view.events_and_notices.yml, config/default/views.view.public_notice.yml
DIG-2163 Extend length of time events / notices stay up in component.
=> DIG-2163 Extend length of time

composer.json, composer.lock, config/default/content_moderation_notifications.content_moderation_notification.notify_content_creator.yml, config/default/content_moderation_notifications.content_moderation_notification.review_content_submitted.yml, config/default/core.extension.yml, config/default/lightning_core.versions.yml, config/default/user.role.content_author.yml, config/default/user.role.content_editor.yml, config/default/user.role.content_reviewer.yml, config/default/user.role.site_administrator.yml
DIG-2164 Add notification for content authors when pages are published
=> DIG-2164 Add notification for content authors

config/default/field.field.node.event.field_email.yml, config/default/field.field.node.event.field_event_contact.yml
DIG-2059 Adjust language for contact information in events
=> DIG-2059 Adjust language for contact information in events

composer.json, config/acquia_dev/config_ignore.settings.yml, config/acquia_dev/salesforce_logger.settings.yml, config/acquia_prod/config_ignore.settings.yml, config/acquia_stage/config_ignore.settings.yml, config/default/config_split.config_split.acquia_dev.yml, config/default/config_split.config_split.local.yml, config/default/node_buildinghousing.settings.yml, config/default/salesforce_mapping.salesforce_mapping.building_housing_project_update.yml, config/local/config_ignore.settings.yml, config/local/salesforce_logger.settings.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.menu.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.routing.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Batch/SalesforceSyncBatch.inc, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-document.html.twig, docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-text.html.twig, docroot/modules/custom/bos_core/bos_core.module, docroot/themes/custom/bos_admin/bos_admin.theme
DIG-465: [building housing dup attachment](https://bostondoit.atlassian.net/browse/DIG-2086)
DIG-1851: [BH: Remove duplicate files from BH Projects](https://bostondoit.atlassian.net/browse/DIG-1851)
DIG-1858: [BH: Web Update chatter comment not showing on BH Project page](https://bostondoit.atlassian.net/browse/DIG-1858)
=> (develop) building housing dup attachment 

config/default/field.field.node.event.field_email.yml, config/default/field.field.node.event.field_event_contact.yml
DIG-2059 - [Adjust language for contact information in events](https://bostondoit.atlassian.net/browse/DIG-2059)
=> (develop) Adjust language for contact information in events - hotfix

docroot/modules/custom/bos_components/modules/bos_email/bos_email.routing.yml, docroot/modules/custom/bos_components/modules/bos_email/src/CobEmail.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/EmailTemplateInterface.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php, docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Registry.php
DIG-2108 [Adjust handling of OOO replies in Postmark](https://bostondoit.atlassian.net/browse/DIG-2108)
=> (develop) Adjust handling of OOO replies in Postmark - hotfix

composer.lock
DIG-2264 [Drupal Maintenance incl core to 9.5.9](https://bostondoit.atlassian.net/browse/DIG-2264)
=> (develop) Drupal Maintenance incl core to 9.5.9

config/acquia_dev/config_split.patch.metatag.metatag_defaults.global.yml, config/acquia_prod/config_split.patch.metatag.metatag_defaults.global.yml, config/acquia_prod/redirect_domain.domains.yml, config/acquia_prod/xmlsitemap.settings.yml, config/acquia_prod/xmlsitemap_engines.settings.yml, config/acquia_stage/config_split.patch.metatag.metatag_defaults.global.yml, config/default/config_split.config_split.acquia_prod.yml, config/default/xmlsitemap.settings.node.bh_project.yml, config/default/xmlsitemap.settings.node.department_profile.yml, config/default/xmlsitemap.settings.node.how_to.yml, config/default/xmlsitemap.settings.node.landing_page.yml, config/default/xmlsitemap.settings.node.listing_page.yml, config/default/xmlsitemap.settings.node.person_profile.yml, config/default/xmlsitemap.settings.node.place_profile.yml, config/default/xmlsitemap.settings.node.post.yml, config/default/xmlsitemap.settings.node.public_notice.yml, config/default/xmlsitemap.settings.node.topic_page.yml, config/default/xmlsitemap.settings.node.transaction.yml
DIG-2282 [Adjust config for domain redirects](https://bostondoit.atlassian.net/browse/DIG-2289)
=> (develop) Search engine issues

config/default/salesforce_mapping.salesforce_mapping.building_housing_projects.yml
DIG-2257 [BH: Project Goals not appearing on Project Page](https://bostondoit.atlassian.net/browse/DIG-2257) - MOH
=> DIG-2257 BH: Project Goals not appearing on Project Page

config/default/bos_email.settings.yml, config/default/core.entity_form_display.paragraph.3_column_w_image.default.yml, config/default/core.entity_form_display.paragraph.cabinet.default.yml, config/default/core.entity_form_display.paragraph.drawers.default.yml, config/default/core.entity_form_display.paragraph.events_and_notices.default.yml, config/default/core.entity_form_display.paragraph.grid_of_quotes.default.yml, config/default/core.entity_form_display.paragraph.grid_of_topics.default.yml, config/default/core.entity_form_display.paragraph.group_of_links_grid.default.yml, config/default/core.entity_form_display.paragraph.group_of_links_list.default.yml, config/default/core.entity_form_display.paragraph.group_of_links_mini_grid.default.yml, config/default/core.entity_form_display.paragraph.group_of_links_quick_links.default.yml, config/default/core.entity_form_display.paragraph.news_and_announcements.default.yml, config/default/core.entity_form_display.paragraph.text.default.yml, config/default/core.entity_form_display.paragraph.transaction_grid.default.yml
DIG-2303 [Refactor config files to prevent re-import during deploy](https://bostondoit.atlassian.net/browse/DIG-2303).
=> (develop) Refactor config files to prevent re-import during deploy. DIG-2303 

config/default/core.entity_form_display.paragraph.drawers.default.yml, config/default/core.entity_form_display.paragraph.grid_of_topics.default.yml, config/default/core.entity_form_display.paragraph.group_of_links_quick_links.default.yml, config/default/core.entity_form_display.paragraph.transaction_grid.default.yml
DIG-2303 [Refactor config files to prevent re-import during deploy](https://bostondoit.atlassian.net/browse/DIG-2303)
=> (develop) Refactor config files to prevent re-import during deploy. DIG-2303

config/default/views.view.metrolist_ami.yml
DIG-2284 [Update AMI limits](https://bostondoit.atlassian.net/browse/DIG-2284)
=> (develop) Update AMI limits

config/default/webform.webform.metrolist_listing.yml, docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
=> (ci) Re-enables (non)Discrimination Checkbox DIG-1368

.github/percy/snapshot_config.yml, docroot/modules/custom/bos_components/modules/bos_card/templates/paragraph--card.html.twig
DIG-2350 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-2350)
=> (develop) hotfix Minor fixes after maintenance updates 

config/default/bos_email.settings.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.module, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkOps.php
DIG-2336 [Reformat and target alert email when postmark hard-bounces](https://bostondoit.atlassian.net/browse/DIG-2336)
=> (develop) Reformat and target alert email when postmark hard-bounces

config/default/content_moderation_notifications.content_moderation_notification.notify_content_creator.yml, config/default/content_moderation_notifications.content_moderation_notification.review_content_submitted.yml, docroot/modules/custom/bos_core/Boston.php, docroot/profiles/bos_profile/bos_profile.install, docroot/sites/default/settings.php, docroot/themes/custom/bos_theme/bos_theme.theme
DIG-1430 [Update SimplSAML on non-prod boston.gov for Acquia Cloud Next upgrade](https://bostondoit.atlassian.net/browse/DIG-1430)
=> (develop) Update SimplSAML on non-prod boston.gov for Acquia  DIG-1430 

config/default/webform.webform.metrolist_listing.yml
DIG-1775 [Drupal update causes error in web forms](https://bostondoit.atlassian.net/browse/DIG-1775) -MOH
=> (develop)(hotfix) Drupal update causes error in web forms DIG-1775

README.md
DIG-1775 [Drupal update causes error in web forms](https://bostondoit.atlassian.net/browse/DIG-1775)
=> (stage) Drupal update causes error in web forms DIG-1775

composer.lock, config/default/bos_email.settings.yml
DIG-2442 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-2442)
=> DIG-2442 Drupal Maintenance

config/default/salesforce_mapping.salesforce_mapping.bh_website_update.yml
DIG-2435 [BH: Missing Follower Emails](https://bostondoit.atlassian.net/browse/DIG-2494) (MOH).
=> (develop) Adds full sync for follower email field DIG-2435

docroot/modules/custom/bos_content/modules/node_elections/src/Controller/ElectionFileUploader.php
DIG-2390 [Confirm new xml files work for unofficial election uploads](https://bostondoit.atlassian.net/browse/DIG-2390)
=> (develop) Adds code to detect excel file formats DIG-2390

docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php, docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
DIG-2527 Contact form template email send fix
=> DIG-2527 Contact form template email send fix

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php
DIG-2651: [Building Housing file attachment not appearing on website](https://bostondoit.atlassian.net/browse/DIG-2651)
=> (develop) Increase SF import max file size to 100MB DIG-2651

composer.json
DIG-2632 - [entity_clone fails on larger pages](https://bostondoit.atlassian.net/browse/DIG-2632)
=> (develop) repatches entity_clone DIG-2632

config/default/webform.webform.website_feedback_form.yml
=> DIG-2603 Tighten up website feedback form

config/default/webform.webform.website_feedback_form.yml
=> DIG-2603 Feedback form update

config/default/webform.webform.website_feedback_form.yml
DIG-2603 : [Tighten up website feedback form](https://bostondoit.atlassian.net/browse/DIG-2603)
=> DIG-2603 Tighten up website feedback form (hotfix)

.travis.yml, docroot/modules/custom/bos_components/bos_components.module, scripts/.config.yml, scripts/deploy/cob_utilities.sh
=> (develop) Post d10 cleanup

composer.json, composer.lock, scripts/deploy/cob_utilities.sh
Adds node_revision_delete module and fixes D10 specific installation code.
=> Post d10 cleanup

config/acquia_dev/key.key.iam_dir_sso_test_.yml, config/acquia_dev/samlauth.authentication.yml, config/acquia_prod/key.key.iam_dir_sso_prod_.yml, config/acquia_prod/samlauth.authentication.yml, config/acquia_stage/key.key.iam_dir_sso_test_.yml, config/acquia_stage/samlauth.authentication.yml, config/local/key.key.iam_dir_sso_test_.yml, config/local/samlauth.authentication.yml, docroot/modules/custom/bos_components/modules/bos_list/bos_list.module, docroot/modules/custom/bos_core/bos_core.services.yml, docroot/modules/custom/bos_core/includes/realname.extensions.inc, docroot/modules/custom/bos_core/includes/samlauth.extensions.inc, docroot/modules/custom/bos_core/src/EventSubscriber/SamlAuthentication.php, docroot/modules/custom/bos_core/src/EventSubscriber/SamlRedirectSubscriber.php, docroot/modules/custom/bos_core/src/Services/Redirect.php, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/user/page--user--login.html.twig, scripts/local/lando-build-patterns.sh
=> (develop) Updates to saml and login pages.

composer.lock, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php
DIG-2848 - BH URL's added to WU chatter not sync
DIG-2860 - Drupal Maintenance
=> (develop) Maintenance and MOH Updates

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php
DIG-2848 [BH: URLS added to WU chatter not appearing](https://bostondoit.atlassian.net/browse/DIG-2848)
=> (develop) (hotfix) Uses mapping last updated date for chatter updates.

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php
DIG-2848 - [BH URL's added to WU chatter not sync](https://bostondoit.atlassian.net/browse/DIG-2848) [MOH]
=> DIG-2848 (hotfix) Fixes lastpull logic

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php
DIG-2848 - [BH URL's added to WU chatter not sync](https://bostondoit.atlassian.net/browse/DIG-2848) [MOH]
=> (stage) (hotfix) Fixes lastpull logic

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Batch/SalesforceSyncBatch.inc, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php
DIG-2887 [Allow metrolist queues to be managed from BH Config form](https://bostondoit.atlassian.net/browse/DIG-2887)
=> (develop) Allow metrolist queues to be managed from BH Config form

README.md
=> DIG-1368 force deploy

docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Batch/SalesforceSyncBatch.inc, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php
DIG-2887 [Allow metrolist queues to be managed from BH Config form](https://bostondoit.atlassian.net/browse/DIG-2887)
=> (stage) Allow metrolist queues to be managed from BH Config form

composer.lock
DIG-2930 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-2930)
=> (develop) Drupal Maintenance DIG-2930

.gitignore, config/acquia_dev/config_ignore.settings.yml, config/acquia_dev/samlauth.authentication.yml, config/acquia_prod/config_ignore.settings.yml, config/acquia_prod/samlauth.authentication.yml, config/acquia_stage/config_ignore.settings.yml, config/acquia_stage/samlauth.authentication.yml, config/local/config_ignore.settings.yml, config/local/key.key.iam_dir_sso_test.yml, config/local/samlauth.authentication.yml
DIG-2895 [Stop SAML and SF configs overwriting on deploy](https://bostondoit.atlassian.net/browse/DIG-2895)
=> (develop)  Stop SAML and SF configs overwriting on deploy DIG-2895

composer.json, composer.lock, scripts/deploy/cob_utilities.sh
DIG-3047: [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3047)
=> Dig 3047 - Drupal Maintenance incl core 10.1.4

docroot/modules/custom/bos_core/bos_core.links.menu.yml, docroot/modules/custom/bos_core/bos_core.routing.yml, docroot/modules/custom/bos_core/src/Form/QueryForm.php
DIG-3093 [Add Content search to site-admins backend.](https://bostondoit.atlassian.net/browse/DIG-3093)
=> (develop) Add Content search to site-admins backend.

config/default/webform.webform.metrolist_listing.yml
DIG-3130 [ML: Update field label on Listing Form](https://bostondoit.atlassian.net/browse/DIG-3130) [MOH]
=> (develop) Update field label on Listing Form DIG-3130

docroot/modules/custom/bos_core/src/Form/QueryForm.php
DIG-3093: [Add Content search to site-admins backend.](https://bostondoit.atlassian.net/browse/DIG-3093)
=> (develop) Add Content search to site-admins backend. DIG-3093

.travis.yml, config/acquia_prod/key.config_override.sf_oauth_prod_consumer_key.yml, config/acquia_prod/key.config_override.sf_oauth_prod_consumer_secret.yml, config/default/config_split.config_split.acquia_dev.yml, config/default/config_split.config_split.acquia_prod.yml, config/default/config_split.config_split.acquia_stage.yml, config/default/config_split.config_split.local.yml, config/local/config_split.patch.ape.settings.yml, config/local/config_split.patch.system.performance.yml, scripts/.config.yml, scripts/deploy/cob_utilities.sh
DIG-3198: [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3198)
=> (develop) Further deploy improvements

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
DIG-3014 Sidebar mobile design
=> DIG-3014 sidebar

docroot/modules/custom/bos_content/modules/node_topic_page/templates/node--topic-page.html.twig, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css, docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
DIG-3014 Mobile sidebar update
=> DIG-3014 Mobile sidebar update

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
=> DIG-3014 Sidebar on mobile

config/default/core.entity_form_display.paragraph.internal_link.default.yml, docroot/modules/custom/bos_components/modules/bos_link/bos_link.module, docroot/modules/custom/bos_components/modules/bos_link/src/Plugin/Field/FieldWidget/COBLinkWidget.php, docroot/modules/custom/bos_core/bos_core.module
DIG-2929: [Add improvements to 'internal' links in components](https://bostondoit.atlassian.net/browse/DIG-2929)
Marked as Hotfix to speed up deploy
Internal url bug fix
=> (develop) Add improvements to 'internal' links in components hotfix DIG-2929 

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
DIG-3014 CSS file update to translate link changes
Also has DIG-3483 in it.
=> DIG-3014 DIG-3483 CSS file update to sidebar and topic nav links

composer.lock, config/acquia_dev/captcha.settings.yml, config/acquia_prod/captcha.settings.yml, config/acquia_stage/captcha.settings.yml, config/travis/captcha.settings.yml, docroot/modules/custom/bos_swiftype/src/Form/SwiftypeSettingsForm.php
DIG-3359 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3359)
=> (develop) Drupal Maintenance

docroot/modules/custom/bos_core/src/BosCoreSyncIconManifestService.php
DIG-3501 [Updates drush biim to display better stats](https://bostondoit.atlassian.net/browse/DIG-3501)
=> (develop) Updates drush biim to display better stats DIG-3501

config/default/core.entity_view_display.node.roll_call_dockets.default.yml, config/default/core.entity_view_display.paragraph.roll_call_vote.default.yml, config/default/core.entity_view_display.taxonomy_term.vocab_city_councillors.default.yml, config/default/core.entity_view_display.taxonomy_term.vocab_votes.default.yml, config/default/paragraphs.paragraphs_type.roll_call_vote.yml, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.install, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.module, docroot/modules/custom/bos_content/modules/node_rollcall/templates/field--node--title--roll-call-dockets.html.twig, docroot/modules/custom/bos_content/modules/node_rollcall/templates/node--roll-call-dockets.html.twig, docroot/themes/custom/bos_admin/css/bos_admin.css, docroot/themes/custom/bos_admin/templates/datetime-wrapper.html.twig
=> DIG-3520 Create City Clerk INput Screen

config/default/content_access.settings.yml, config/default/rabbit_hole.behavior_settings.node_type_roll_call_dockets.yml, config/default/user.role.city_clerk_editor.yml, config/default/user.role.content_editor.yml, config/default/user.role.site_administrator.yml
Updates Permissions DIG-3520 into DIG-3517
=> DIG-3520 Create City-Clerk input screen for rollcall vote component

config/default/views.view.roll_call_dockets.yml, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.routing.yml, docroot/modules/custom/bos_content/modules/node_rollcall/src/Controller/Uploader.php, docroot/modules/custom/bos_content/modules/node_rollcall/src/Plugin/views/style/RollcallExportSerializer.php
=> DIG-3522 Migrate Rollcall Data from cityofboston.gov

composer.lock
DIG-3683 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3683)
=> (develop) Drupal Maintenance DIG-3683

docroot/modules/custom/bos_content/modules/node_rollcall/css/roll_call.css
Fix for mobile padding of search action buttons.
=> DIG-3517 mobile css for action buttons.

config/default/core.entity_view_display.paragraph.branded_links.default.yml, docroot/modules/custom/bos_components/modules/bos_branded_links/bos_branded_links.module, docroot/themes/custom/bos_admin/bos_admin.theme
DIG-3701 [The word "off" appearing in resuable paragraph footers](https://bostondoit.atlassian.net/browse/DIG-3701)
=> (develop) The word "off" appearing in resuable paragraph footers DIG-3701

config/default/user.role.city_clerk_editor.yml, config/default/user.role.developer.yml, config/default/user.role.site_administrator.yml
Hotfix to fix config issue on stage
=> (stage) Config fix (hotfix)

docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig
DIG-3308 Add back default message for canceled events
=> DIG-3308 Add back default message for canceled events

.travis.yml
DIG-3308 Triggering Travis for Acquia deploy
=> (UAT) Triggering Travis for Acquia deploy

docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Assessing.php, docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Pdf.php, docroot/modules/custom/bos_components/modules/bos_pdfmanager/src/Controller/PdfManager.php, docroot/modules/custom/bos_components/modules/bos_sql/src/Controller/SQL.php
DIG-3313 Update Assessing Online database for January 2024 (hotfix)
=> (develop) Update Assessing Online DIG-3313  (hotfix)

docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Assessing.php, docroot/modules/custom/bos_components/modules/bos_assessing/src/Controller/Pdf.php, docroot/modules/custom/bos_components/modules/bos_pdfmanager/src/Controller/PdfManager.php, docroot/modules/custom/bos_components/modules/bos_sql/src/Controller/SQL.php, docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig
DIG-3313 Update Assessing Online database for January 2024 (hotfix)
=> (stage) Update Assessing Online DIG-3313  (hotfix)

docroot/modules/custom/bos_core/bos_core.libraries.yml, docroot/modules/custom/bos_core/includes/moderation_sidebar.extensions.inc, docroot/modules/custom/bos_core/js/bos_core_mod_sidebar.js
DIG-3309 [Moderation sidebar textarea required,](https://bostondoit.atlassian.net/browse/DIG-3309)
=> (develop) Moderation sidebar textarea required DIG-3309

docroot/modules/custom/bos_components/modules/bos_mnl/src/Controller/MNLRest.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessImport.php, docroot/modules/custom/bos_components/modules/bos_mnl/src/Plugin/QueueWorker/MNLProcessUpdate.php
DIG-3820 [Reset My Neighborhood Lookup to reflect updated City Council information](https://bostondoit.atlassian.net/browse/DIG-3820)
=> DIG-3820 Legacy bug fixes to endpoint.

composer.json, composer.lock
DIG-3834 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3834)
=> (develop) Drupal Maintenance DIG-3834

composer.json, config/default/core.entity_form_display.node.post.default.yml, config/default/views.view.news_and_announcements.yml, docroot/modules/custom/bos_components/modules/bos_news_and_announcements/bos_news_and_announcements.module
Add option to "Select all" of a specific "place" type in "related content"
=> DIG-3026 Select all in related content

composer.json
DIG-3834 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3834)
=> (develop)  patch for jquery error in module_filter DIG-3834

composer.lock
DIG-3888 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-3888)
=> (develop) Drupal Maintenance DIG-3888

docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module
DIG-3890 Select All Related Content
=> (UAT) DIG-3890 Select All Related Content

config/default/core.entity_form_display.node.event.default.yml, config/default/core.entity_view_display.node.event.add_to_calendar.yml, config/default/core.entity_view_display.node.event.default.yml, config/default/core.entity_view_display.node.event.featured_item.yml, config/default/field.field.node.event.field_place_type.yml, config/default/user.role.authenticated.yml, config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module
DIG-3890 Select All Related Content
=> (develop) DIG-3890 Select All Related Content

composer.json, composer.lock, docroot/modules/custom/bos_core/bos_core.module
DIG-3951 [Drupal Maintenance ](https://bostondoit.atlassian.net/browse/DIG-3951)
=> (develop) Drupal Maintenance DIG-3951

docroot/modules/custom/bos_components/modules/bos_emergency_alerts/bos_emergency_alerts.routing.yml, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/bos_emergency_alerts.services.yml, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/ApiRouter.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EmergencyAlertsSubscriberBase.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EverbridgeSubscriber.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/GenasysSubscriber.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/EmergencyAlertsAPISettingsInterface.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Event/EmergencyAlertsBuildFormEvent.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Event/EmergencyAlertsSubmitFormEvent.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Event/EmergencyAlertsValidateFormEvent.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Form/EmergencyAlertsSettingsForm.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/templates/paragraph--bos-signup-emergency-alerts.html.twig, docroot/modules/custom/bos_core/bos_core.module
DIG-3839 [Alert Boston API integration of Genasys with Drupal](https://bostondoit.atlassian.net/browse/DIG-3839)
=> (develop) Genasys API for Emergency Alerts DIG-3839 

docroot/modules/custom/bos_components/css/component-theme.css
DIG-3979 Blue text not appearing on white background in components
=> (develop) DIG-3979 Blue text not appearing on white background in components

.gitignore, config/default/bos_emergency_alerts.settings.yml, config/default/bos_geocoder.settings.yml, config/default/core.extension.yml, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EmergencyAlertsSubscriberBase.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/EverbridgeSubscriber.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/GenasysSubscriber.php, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Form/EmergencyAlertsSettingsForm.php, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.info.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.module, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.routing.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.task.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/src/Controller/BosGeocoder.php, docroot/modules/custom/bos_components/modules/bos_geocoder/src/Form/GeocoderConfigForm.php, docroot/modules/custom/bos_components/modules/bos_geocoder/src/Utility/BosGeoAddress.php, docroot/modules/custom/bos_components/modules/bos_geocoder/src/Utility/BosGeoCoords.php, docroot/modules/custom/bos_core/src/Controllers/Curl/BosCurlControllerBase.php, docroot/modules/custom/bos_core/src/Controllers/Settings/CobSettings.php
DIG-3839[ Alert Boston API integration of Genasys with Drupal](https://bostondoit.atlassian.net/browse/DIG-3839)
=> (develop) Adds geocoding to emergency alerts DIG-3839

docroot/modules/custom/bos_components/modules/bos_emergency_alerts/src/Controller/GenasysSubscriber.php, docroot/themes/custom/bos_admin/bos_admin.theme
DIG-3839 [Alert Boston API integration of Genasys with Drupal](https://bostondoit.atlassian.net/browse/DIG-3839)
=> (develop) Hotfix for subscribe error on DIG-3839

config/default/core.entity_form_display.node.department_profile.default.yml, config/default/core.entity_view_display.node.department_profile.article.yml, config/default/core.entity_view_display.node.department_profile.calendar_listing.yml, config/default/core.entity_view_display.node.department_profile.card.yml, config/default/core.entity_view_display.node.department_profile.contact.yml, config/default/core.entity_view_display.node.department_profile.default.yml, config/default/core.entity_view_display.node.department_profile.department_listing.yml, config/default/core.entity_view_display.node.department_profile.featured_item.yml, config/default/core.entity_view_display.node.department_profile.featured_topics.yml, config/default/core.entity_view_display.node.department_profile.icon_popup.yml, config/default/core.entity_view_display.node.department_profile.listing.yml, config/default/core.entity_view_display.node.department_profile.listing_long.yml, config/default/core.entity_view_display.node.department_profile.poll_stub.yml, config/default/core.entity_view_display.node.department_profile.popup_icon.yml, config/default/core.entity_view_display.node.department_profile.published_by.yml, config/default/core.entity_view_display.node.department_profile.teaser.yml, config/default/core.entity_view_display.node.department_profile.topics_list.yml, config/default/field.field.node.department_profile.field_link_url.yml, config/default/field.field.node.department_profile.field_select_contact_type.yml, config/default/field.storage.node.field_link_url.yml, config/default/field.storage.node.field_select_contact_type.yml, docroot/modules/custom/bos_content/modules/node_department_profile/node_department_profile.module, docroot/modules/custom/bos_content/modules/node_department_profile/templates/fieldset-field-select-contact-type.html.twig, docroot/modules/custom/bos_content/modules/node_department_profile/templates/node--department-profile.html.twig
DIG-3428
Add link option to replace contact email in department profile pages
=> DIG-3428 Add link option to replace contact email in department profile pages

config/default/salesforce_mapping.salesforce_mapping.bh_community_meeting_event.yml, config/default/salesforce_mapping.salesforce_mapping.bh_parcel_project_assoc.yml, config/default/salesforce_mapping.salesforce_mapping.bh_website_update.yml, config/default/salesforce_mapping.salesforce_mapping.building_housing_parcels.yml, config/default/salesforce_mapping.salesforce_mapping.building_housing_projects.yml
DIG-3715 [Update drupal logic to use new "Web Page Status" field to display project pages on map](https://bostondoit.atlassian.net/browse/DIG-3715)
=> (develop) Updates config for SF=>Drupal push workflows. DIG-3715

docroot/modules/custom/bos_content/modules/node_department_profile/templates/node--department-profile.html.twig
DIG-3428 Add link option to replace contact email in department profile pages
=> DIG-3428 Add link option to replace contact email in department

config/default/core.entity_view_display.node.election_report.default.yml, docroot/modules/custom/bos_content/modules/node_elections/src/Controller/ElectionFileUploader.php, docroot/modules/custom/bos_content/modules/node_elections/src/Form/ElectionUploaderForm.php
DIG-4111 [Investigate issues with unofficial election results data ](https://bostondoit.atlassian.net/browse/DIG-4111)
=> (dev) Investigate issues with unofficial election results data DIG-4111

docroot/modules/custom/bos_content/modules/node_elections/node_elections.module, docroot/modules/custom/bos_content/modules/node_elections/src/Controller/ElectionFileUploader.php, docroot/modules/custom/bos_content/modules/node_elections/src/ElectionUtilities.php, docroot/modules/custom/bos_content/modules/node_elections/src/Form/ElectionUploaderForm.php
DIG-4111 [Investigate issues with unofficial election results data](https://bostondoit.atlassian.net/browse/DIG-4111)
=> (develop) Election Results Performance Improvements DIG-4111

docroot/modules/custom/bos_components/css/component-theme.css
DIG-4170 Listing Page Filter Drawer updates for mobile
=> DIG-4170 Listing Page Filter Drawer updates for mobile

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/dist/index.bundle.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/FilterGroup/index.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/FiltersPanel/index.js
DIG-1777 Listing Page Filter Drawer updates for mobile
=> DIG-1777 Listing Page Filter Drawer updates for mobile

docroot/modules/custom/slackposter/src/Logger/SlackLogger.php
DIG-4251 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4251)
=> (develop) (hotfix) Fixes slacklogger runtime error

docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Commands/GcApiDrushCommands.php, docroot/modules/custom/bos_core/bos_core.module
DIG-4272 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4272)
DIG-4261 [Document links without titles causing error](https://bostondoit.atlassian.net/browse/DIG-4261)
=> (develop) (hotfix) Runtime error when no doc title DIG-4261

docroot/themes/custom/bos_theme/templates/snippets/secondary-nav.html.twig
DIG-4260 [Update feedback link in top navigation](https://bostondoit.atlassian.net/browse/DIG-4260)
=> (develop) (hotfix) Update feedback link in top navigation DIG-4260

config/acquia_prod/redirect_domain.domains.yml
DIG-4290 [Set up config for domain redirects to point to new budget site](https://bostondoit.atlassian.net/browse/DIG-4290)
=> (develop) (hotfix) Set up config for domain redirects to point to new budget site DIG-4290

config/acquia_dev/config_ignore.settings.yml, config/acquia_dev/samlauth.authentication.yml, config/acquia_prod/config_ignore.settings.yml, config/acquia_stage/config_ignore.settings.yml, config/acquia_stage/samlauth.authentication.yml, config/default/blobk.block.bos_theme_feedbackform.yml, config/default/block.block.ml_listing_entry.yml, config/default/block.block.website_feedback_form.yml, config/default/field.field.node.program_initiative_profile.field_components.yml, config/default/locale.settings.yml, config/local/samlauth.authentication.yml, docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Controller/GcApiEndpointTester.http, docroot/modules/custom/bos_content/modules/node_rollcall/src/Controller/node_rollcall_endpoints.http
DIG-4272 [Fix deploy pipeline due to next cloud update](https://bostondoit.atlassian.net/browse/DIG-4272)
=> (develop) Fix deploy pipeline due to next cloud update DIG-4272

composer.json, composer.lock, patches/3088544-11.patch
DIG-4300 [Drupal Maintenance ](https://bostondoit.atlassian.net/browse/DIG-4300)
=> (develop) Drupal Maintenance DIG-4300

docroot/modules/custom/bos_components/css/component-theme.css
DIG-4282 [Review and confirm text for blue theming of components](https://bostondoit.atlassian.net/browse/DIG-4282)
=> (develop) Review and confirm text for blue theming of components DIG-4282 

docroot/modules/custom/bos_core/src/Commands/BosCoreCommands.php
DIG-4307 [Fix Icon Manifest Importer](https://bostondoit.atlassian.net/browse/DIG-4307)
=> (develop) Fix Icon Manifest Importer DIG-4307

docroot/modules/custom/bos_content/modules/node_article/templates/node--article.html.twig, docroot/modules/custom/bos_content/modules/node_how_to/templates/node--how-to.html.twig
required in 'article' and 'how-to' pages; display optional
=> DIG-4158 Make department contact field

config/default/views.view.public_notice.yml
DIG-4316 [Timestamp mis-reported on public notices webapp](https://bostondoit.atlassian.net/browse/DIG-4316).
=> (develop) Timestamp mis-reported on public notices webapp. DIG-4316

docroot/modules/custom/bos_content/modules/node_status_item/src/Plugin/views/style/Bos311Serializer.php
DIG-4340 [Fix for API to Correct 311 Mobile App Status of City Services](https://bostondoit.atlassian.net/browse/DIG-4340)
=> (develop) Fix for API to Correct 311 Mobile App Status of City Services DIG-4340

.travis.yml, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/dist/index.bundle.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/FiltersPanel/index.js
DIG-4295 ML: Listing page Clear Filters box updates
=> DIG-4295 ML: Listing page Clear Filters box updates

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/dist/index.bundle.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/ClearFiltersButton/index.js, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/FiltersPanel/index.js
DIG-4295 ML: Listing page Clear Filters box updates
=> (DEV2) Listing page Clear Filters box updates DIG-4295

config/default/bos_google_cloud.prompts.yml, docroot/modules/custom/bos_core/src/Commands/BosCoreCommands.php
DIG-4373 [Altered prompting](https://bostondoit.atlassian.net/browse/DIG-4373).
=> (develop) Altered prompting DIG-4373

docroot/modules/custom/bos_components/modules/bos_web_app/apps/sanitation_scheduling/sanitation_scheduling.libraries.yml, docroot/modules/custom/bos_components/modules/bos_web_app/apps/sanitation_scheduling/sanitation_scheduling.module
DIG-4213  [Allows prod toggle for CDN switching](https://bostondoit.atlassian.net/browse/DIG-4213).
=> (CI) Allows prod toggle for CDN switching. DIG-4213 

config/default/field.field.node.article.field_components.yml, docroot/modules/custom/bos_components/modules/bos_translate/bos_translate.libraries.yml, docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
DIG-4393 [Translation fix for Mattress App Embed](https://bostondoit.atlassian.net/browse/DIG-4393)
DIG-4213 [Enables bos_web_apps component on Articles](https://bostondoit.atlassian.net/browse/DIG-4213)
=> (develop) Translation fix for Mattress App Embed DIG-4393

config/default/bos_google_cloud.prompts.yml, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.module, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.routing.yml, docroot/modules/custom/bos_content/modules/node_rollcall/src/Controller/Downloader.php, docroot/modules/custom/bos_content/modules/node_rollcall/src/Controller/node_rollcall_endpoints.http
DIG-4373 [Create beta site for Generative AI summarized roll call votes](https://bostondoit.atlassian.net/browse/DIG-4373).
=> (develop) download AI experiments DIG-4373

docroot/modules/custom/bos_components/modules/bos_web_app/templates/paragraph--web-app.html.twig
Adds a fixed anchor to top of webapp component.
DIG-4428 [Create a permanent anchor for sanitation web-app scrolling](https://bostondoit.atlassian.net/browse/DIG-4428)
=> (develop) Create a permanent anchor for sanitation web-app scrolling DIG-4428

config/default/block.block.bos_theme_feedbackform.yml, config/default/block.block.bos_theme_views_block__emergency_alerts_block_emergency_alert.yml, config/default/block.block.bos_theme_views_block__site_alerts_block_site_alerts.yml, config/default/block.block.mainmenu.yml, config/default/block.block.mainpagecontent.yml, config/default/block.block.ml_listing_entry.yml, config/default/block.block.webform.yml, config/default/block.block.website_feedback_form.yml, config/default/core.entity_form_display.node.emergency_alert.default.yml, config/default/core.entity_form_display.node.site_alert.default.yml, config/default/core.entity_view_display.node.site_alert.default.yml, config/default/core.entity_view_display.node.site_alert.embed.yml, config/default/core.entity_view_display.node.site_alert.teaser.yml, config/default/field.field.node.site_alert.field_excluded_nodes.yml, config/default/field.field.node.site_alert.field_included_nodes.yml, config/default/views.view.emergency_alerts.yml, config/default/views.view.site_alerts.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module, docroot/modules/custom/bos_content/modules/node_emergency_alert/css/emergency_alert.boston.css, docroot/modules/custom/bos_content/modules/node_emergency_alert/node_emergency_alert.module, docroot/modules/custom/bos_content/modules/node_emergency_alert/templates/block--views-block--emergency-alerts-block-emergency-alert.html.twig, docroot/modules/custom/bos_content/modules/node_emergency_alert/templates/node--emergency-alert.html.twig, docroot/modules/custom/bos_content/modules/node_site_alert/config/install/core.entity_view_display.node.site_alert.default.yml, docroot/modules/custom/bos_content/modules/node_site_alert/css/site-alert.boston.css, docroot/modules/custom/bos_content/modules/node_site_alert/node_site_alert.module, docroot/modules/custom/bos_content/modules/node_site_alert/templates/node--site-alert.html.twig, docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/templates/layout/page.html.twig
DIG-4391 [Adjust display logic for 'site alerts' content type](https://bostondoit.atlassian.net/browse/DIG-4391)
=> (develop) Adjust display logic for 'site alerts' content type DIG-4391

.gitignore, docroot/modules/custom/bos_components/modules/bos_email/bos_email.http
=> (develop) Moves http (rest testing) into private repo and ignores file

composer.lock, config/default/views.view.roll_call_dockets.yml, docroot/modules/custom/bos_components/modules/bos_email/src/Controller/EmailController.php, docroot/modules/custom/bos_components/modules/bos_email/src/Services/TokenOps.php
DIG-4448 [Drupal Maintenance ](https://bostondoit.atlassian.net/browse/DIG-4448)
=> (develop) Drupal Maintenance DIG-4448

docroot/modules/custom/bos_components/modules/bos_email/bos_email.module
DIG-4448 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4448)
=> (develop) Drupal Maintenance DIG-4448 

docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module
DIG-4405 [Fix Project Goals in timeline](https://bostondoit.atlassian.net/browse/DIG-4405)
=> (develop) Fix Project Goals in timeline DIG-4405 

docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php
DIG-4405: [Project Summaries fail to show](https://bostondoit.atlassian.net/browse/DIG-4405)
=> (develop) Project Summaries fail to show DIG-4405

docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.services.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/BhEntityEventSubscriber.php
DIG-4405: [Project Summaries fail to show](https://bostondoit.atlassian.net/browse/DIG-4405)
=> (develop) Adds default body on entity load DIG-4405

docroot/modules/custom/bos_components/modules/bos_email/src/Plugin/EmailProcessor/Contactform.php
DIG-4511 [Postmark emails missing contact information](https://bostondoit.atlassian.net/browse/DIG-4511)
=> (develop) Postmark emails missing contact information DIG-4511

composer.json, composer.lock
DIG-4455 [Add CAPTCHA to Boston.gov feedback form](https://bostondoit.atlassian.net/browse/DIG-4455)
=> (develop) Add CAPTCHA to Boston.gov feedback form DIG-4455

composer.lock
DIG-4544 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4544)
Upgrading chi-teck/drupal-code-generator (3.5.0 => 3.6.0)
Upgrading composer/class-map-generator (1.1.1 => 1.3.2)
Upgrading composer/pcre (3.1.3 => 3.1.4)
Upgrading doctrine/event-manager (2.0.0 => 2.0.1)
Upgrading drupal/acquia_connector (4.0.6 => 4.0.7)
Upgrading drupal/autologout (1.4.0 => 1.5.0)
Upgrading drupal/better_exposed_filters (6.0.5 => 6.0.6)
Upgrading drupal/blazy (2.26.0 => 2.27.0)
Upgrading drupal/core (10.2.6 => 10.2.7)
Upgrading drupal/core-dev (10.2.6 => 10.2.7)
Upgrading drupal/diff (1.3.0 => 1.4.0)
Upgrading drupal/draggableviews (2.1.3 => 2.1.4)
Upgrading drupal/environment_indicator (4.0.17 => 4.0.18)
Upgrading drupal/jquery_ui (1.6.0 => 1.7.0)
Upgrading drupal/jquery_ui_accordion (2.0.0 …
=> (develop) Drupal Maintenance DIG-4544

config/default/core.entity_form_display.node.program_initiative_profile.default.yml, config/default/field.field.node.program_initiative_profile.field_contacts.yml, config/default/field.field.node.program_initiative_profile.field_program_type.yml, config/default/pathauto.pattern.program_initiative_profile_path.yml
DIG-4553 - [Program initiatives Profile Contacts field](https://bostondoit.atlassian.net/browse/DIG-4553)
=> (develop) Program initiatives Profile Contacts field DIG-4553 

config/acquia_dev/key.key.iam_dir_sso.yml, config/acquia_dev/samlauth.authentication.yml, config/acquia_prod/key.key.iam_dir_sso_test.yml, config/acquia_prod/samlauth.authentication.yml, config/acquia_stage/key.key.iam_dir_sso.yml, config/acquia_stage/key.key.iam_dir_sso_test_.yml, config/acquia_stage/samlauth.authentication.yml, config/default/config_split.config_split.acquia_dev.yml, config/default/config_split.config_split.acquia_prod.yml, config/default/config_split.config_split.acquia_stage.yml
DIG-4590 [Updates config for SAML](https://bostondoit.atlassian.net/browse/DIG-4590)
=> (develop) Updates config for SAML DIG-4590

config/default/views.view.status_items.yml, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module, docroot/modules/custom/bos_content/modules/node_status_item/src/Plugin/views/style/Bos311Serializer.php
DIG-4638 [Look into date error in 311 app](https://bostondoit.atlassian.net/browse/DIG-4638)
=> (develop) Look into date error in 311 app DIG-4638

composer.json, composer.lock, config/acquia_prod/google_tag.container.default_gtm.yml, config/acquia_prod/google_tag.settings, config/default/config_split.config_split.acquia_prod.yml
DIG-4667 [Google Analytics Disconnected from Boston.gov ](https://bostondoit.atlassian.net/browse/DIG-4667)
=> (develop) Google Analytics Disconnected from Boston.gov DIG-4667

RELEASE.md
This re-runs the Percy Github Action after (re)applying css changes.
=> chore: force a github action

.github/workflows/D10-Deploy.yml
tests adding the ci-no-deploy flag
=> chore: Adds no-deploy label handler to deploy.

config/default/views.view.status_items.yml, docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module, docroot/modules/custom/bos_content/modules/node_status_item/src/Plugin/views/style/Bos311Serializer.php
Reverts CityOfBoston/boston.gov-d8#3511.
Reverting this because the altered view times-out and/or runs out of memory on Acquia environments. Re-opening the Jira ticket.
DIG-4638 [Look into date error in 311 app](https://bostondoit.atlassian.net/browse/DIG-4638)
=> (develop) Revert "Look into date error in 311 app" DIG-4638

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
DIG-4741
Adjust text color of 'Emergency Alert' content type
=> DIG-4741 Adjust text color of 'Emergency Alert' content type

docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
DIG-4741
Adjust text color of 'Emergency Alert' content type
=> (develop) DIG-4741 - Adjust text color of 'Emergency Alert' content type

composer.json, composer.lock
DIG-4832 [Drupal Maintenance incl core 10.3.1](https://bostondoit.atlassian.net/browse/DIG-4832)
=> (develop) Drupal Maintenance incl core 10.3.1 DIG-4832

composer.json, patches/core_2230909_updatehook.patch
DIG-4832 Adds patch to fix decimal patch on core 2230909-325
Cause by patches added to core as part of decimal issue 2230909 and (probably) as part of 10.3.x minor upgrade
=> (develop)  Adds patch to fix decimal patch on core 2230909-325: DIG-4832

composer.json, composer.lock
DIG-4832[ Adds patch to fix lightnng_workflow v10.3.x issues](https://bostondoit.atlassian.net/browse/DIG-4832)
=> (develop) Adds patch to fix lightnng_workflow v10.3.x issues DIG-4832

config/acquia_prod/config_ignore.settings.yml, config/default/views.view.workbench_content_listings.yml, config/default/views.view.workbench_recent_content.yml, docroot/modules/custom/bos_content/bos_content.libraries.yml, docroot/modules/custom/bos_content/bos_content.module, docroot/modules/custom/bos_content/css/button_icons.css, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/config/install/views.view.bos_dashboards.yml, docroot/modules/custom/bos_content/modules/node_procurement_advertisement/node_procurement_advertisement.info.yml, docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.links.menu.yml, docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.routing.yml, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.links.menu.yml, docroot/modules/custom/bos_content/modules/node_rollcall/node_rollcall.routing.yml
DIG-4630 [Improvements to roll call creation experience](https://bostondoit.atlassian.net/browse/DIG-4630)
DIG-4631 [Add direct links to specific content types in My Workbench menu for City Clerk Editor role](https://bostondoit.atlassian.net/browse/DIG-4631)
DIG-4632 [Add "Roll Call Dockets" as an option in "All Recent Content" menu item](https://bostondoit.atlassian.net/browse/DIG-4632)
DIG-4633 [Change default selection in Roll Call Dockets from "none" to "yes" ](https://bostondoit.atlassian.net/browse/DIG-4633)
=> (develop) Improvements to roll call creation experience DIG-4630

composer.json, patches/dig-4845.patch
DIG-4845 [Icon upload broken in 'transaction grid' component](https://bostondoit.atlassian.net/browse/DIG-4845)
=> (develop) Icon upload broken in 'transaction grid' component DIG-4845

docroot/modules/custom/bos_components/modules/bos_city_score/bos_city_score.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.links.task.yml, docroot/modules/custom/bos_components/modules/bos_email/bos_email.routing.yml, docroot/modules/custom/bos_components/modules/bos_emergency_alerts/bos_emergency_alerts.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_geocoder/bos_geocoder.links.task.yml, docroot/modules/custom/bos_components/modules/bos_google_cloud/bos_google_cloud.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_google_cloud/bos_google_cloud.links.task.yml, docroot/modules/custom/bos_components/modules/bos_mnl/bos_mnl.links.menu.yml, docroot/modules/custom/bos_components/modules/bos_mnl/bos_mnl.links.task.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.menu.yml, docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.task.yml, docroot/modules/custom/bos_core/bos_core.links.menu.yml, docroot/modules/custom/bos_core/bos_core.links.task.yml
Unifies Boston Custom module menus under single `Boston Configurations` menu item in `Configuration` backend.
=> (develop) Unifies Boston Custom module menus

docroot/modules/custom/bos_components/modules/bos_search/bos_search.module, docroot/modules/custom/bos_components/modules/bos_search/css/ai_feedback.css, docroot/modules/custom/bos_components/modules/bos_search/css/bos_search.css, docroot/modules/custom/bos_components/modules/bos_search/css/grid_of_cards.css, docroot/modules/custom/bos_components/modules/bos_search/css/search_bar.css, docroot/modules/custom/bos_components/modules/bos_search/includes/aisearch_form_theme.inc, docroot/modules/custom/bos_components/modules/bos_search/includes/bos_theme_theme.inc, docroot/modules/custom/bos_components/modules/bos_search/js/bos_search.js, docroot/modules/custom/bos_components/modules/bos_search/src/AiSearchResponse.php, docroot/modules/custom/bos_components/modules/bos_search/src/Form/AiSearchConfigForm.php, docroot/modules/custom/bos_components/modules/bos_search/src/Form/AiSearchForm.php, docroot/modules/custom/bos_components/modules/bos_search/templates/components/search-bar.html.twig, docroot/modules/custom/bos_components/modules/bos_search/templates/search_results/default-results-template.html.twig, docroot/modules/custom/bos_components/modules/bos_search/templates/snippets/aisearch-button.html.twig, docroot/modules/custom/bos_components/modules/bos_search/templates/snippets/aisearch-feedback.html.twig
[see jira comment](https://bostondoit.atlassian.net/browse/DIG-4627?focusedCommentId=33069)
=> DIG-4627 Updates from design team feedback and figma notes.

docroot/modules/custom/bos_components/modules/bos_sidebar/templates/paragraph--sidebar-item-w-icon.html.twig
Fix Google Translate Spanish translation error for email addresses
=> DIG-4874 Fix Google Translate Spanish translation error for email

config/default/editor.editor.basic_html.yml, config/default/editor.editor.rich_text.yml, config/default/taxonomy.vocabulary.bid_offering.yml, config/default/taxonomy.vocabulary.bid_type.yml, config/default/taxonomy.vocabulary.content_feed.yml, config/default/taxonomy.vocabulary.icons.yml, config/default/taxonomy.vocabulary.newsletters.yml, config/default/taxonomy.vocabulary.political_party.yml, config/default/taxonomy.vocabulary.procurement_footer.yml, config/default/taxonomy.vocabulary.procurement_type.yml, config/default/taxonomy.vocabulary.profile_type.yml, config/default/views.view.archive.yml, config/default/views.view.bhmaps.yml, config/default/views.view.building_housing_updates.yml, config/default/views.view.content.yml, config/default/views.view.content_feed.yml, config/default/views.view.file_entity_files.yml, config/default/views.view.roll_call_dockets.yml
DIG-4912 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4912)
=> (develop) DIG-4912 Drupal Maintenance

docroot/modules/custom/bos_components/modules/bos_feedback_form/templates/block--bos-feedback-form.html.twig, docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig, docroot/themes/custom/bos_theme/templates/snippets/secondary-nav.html.twig
=> DIG-4889 Translate form error

composer.json, composer.lock
DIG-4912 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-4912)
=> (develop) DIG-4912: Prevents drupal/embed for upgrading to 1.8.0.

docroot/modules/custom/bos_components/modules/bos_newsletter/templates/paragraph--newsletter--sidebar.html.twig, docroot/modules/custom/bos_components/modules/bos_newsletter/templates/paragraph--newsletter.html.twig, docroot/themes/custom/bos_theme/templates/snippets/contactFormTemplate.html.twig
DIG-4889 Fix Google Translate translation error popup
=> DIG-4889 Fix Google Translate translation error popup

docroot/modules/custom/bos_components/modules/bos_google_cloud/modules/bos_gc_aisearch_plugin/src/Plugin/AiSearch/GcVertexConversation.php, docroot/modules/custom/bos_components/modules/bos_google_cloud/src/GcGenerationPayload.php, docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Services/GcConversation.php, docroot/modules/custom/bos_components/modules/bos_google_cloud/src/Services/GcSearch.php, docroot/modules/custom/bos_components/modules/bos_search/readme.md, docroot/modules/custom/bos_components/modules/bos_search/src/AiSearchRequest.php, docroot/modules/custom/bos_components/modules/bos_search/src/AiSearchResponse.php, docroot/modules/custom/bos_components/modules/bos_search/src/Controller/AiSearchFormController.php, docroot/modules/custom/bos_components/modules/bos_search/src/Form/AiSearchConfigForm.php, docroot/modules/custom/bos_components/modules/bos_search/src/Form/AiSearchForm.php, docroot/modules/custom/bos_components/modules/bos_search/templates/search_results/default-results-template.html.twig
=> (UAT) Adds settings from config form, adds model selection to GcConversation DIG-4627

composer.json
Adds patch to fix date_recur issue DIG-4918
=> (stage) (hotfix) Update composer.json DIG-4918

composer.json, config/default/field.field.node.event.field_event_date_recur.yml
DIG-4918 [Unable to upload intro / thumbnail images to events](https://bostondoit.atlassian.net/browse/DIG-4918)
=> (develop) Fix icon upload/date_recur DIG-4918

composer.json
[DIG-4918](https://bostondoit.atlassian.net/browse/DIG-4918)
[DIG-4918]: https://bostondoit.atlassian.net/browse/DIG-4918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (stage) Fix for icon upload/date recur DIG-4918

config/default/core.entity_view_display.node.department_profile.article.yml, config/default/core.entity_view_display.node.department_profile.default.yml, docroot/modules/custom/bos_content/modules/node_article/templates/node--department-profile--article.html.twig, docroot/modules/custom/bos_content/modules/node_how_to/templates/node--department-profile--article.html.twig
DIG-4868 Default contact link not reflected in department pages
=> DIG-4868 Default contact link not reflected in department pages

config/default/core.extension.yml
=> DIG-4655 - Moderation Dashboard

config/default/field.field.paragraph.video.field_is_channel.yml, docroot/modules/custom/bos_components/modules/bos_video/bos_video.module
DIG-5025 Hide YouTube channel question in 'video' component
=> DIG-5025 Hide YouTube channel question in 'video' component

docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js, docroot/themes/custom/bos_theme/templates/snippets/secondary-nav.html.twig
DIG-5116 Remove Covid 19 statements from website
=> (Develop) DIG-5116 Add data-nosnippet to translation block

composer.json, composer.lock, config/default/core.extension.yml, config/default/xmlsitemap.settings.node.article.yml, config/default/xmlsitemap.settings.node.event.yml, config/default/xmlsitemap.settings.node.procurement_advertisement.yml, config/default/xmlsitemap.settings.node.program_initiative_profile.yml, config/default/xmlsitemap.settings.node.transaction.yml, config/default/xmlsitemap.settings.yml, config/default/xmlsitemap_engines.settings.yml, docroot/themes/custom/bos_theme/templates/layout/html.html.twig
**chore:** Removes** hard coded Google site verification - This should stop non-prod sites contributing to GA.  Check GA after update
**chore:** Enables syslog module for prod
**chore:** Updates XMLSiteMap configs
DIG-5113 [Maintenance package updates](https://bostondoit.atlassian.net/browse/DIG-5113)
=> (develop) DIG-5113 Drupal Maintenance

docroot/modules/custom/bos_content/modules/node_elections/templates/paragraph--election-contest-results--election-card.html.twig
DIG-5100 [Remove columns from elections card](https://bostondoit.atlassian.net/browse/DIG-5100)
=> (develop) Remove columns from elections card DIG-5100 

docroot/themes/custom/bos_admin/bos_admin.libraries.yml, docroot/themes/custom/bos_admin/css/bos_admin.css
DIG-4935 Remove 'never' option for recurring events in Drupal
=> DIG-4935 Remove 'never' option for recurring events in Drupal

docroot/themes/custom/bos_theme/bos_theme.theme, docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
DIG-5063 Replace SVG embed with svg image
=> DIG-5063 Replace SVG embed with svg image

config/default/webform.webform.website_feedback_form.yml
DIG-5188 [Review captcha on Boston.gov feedback form](https://bostondoit.atlassian.net/browse/DIG-5188?atlOrigin=eyJpIjoiZmY4ZDU0Zjc4OTY4NDZmZTlmY2I5ZDQ1Mzk3MmI0ZGQiLCJwIjoiaiJ9)
=> (develop) Review captcha on Boston.gov feedback form DIG-5188

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/metrolist.libraries.yml, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/update-config.sh
Fixed error in previously deployed instance: YAML files cannot contain tabs as indentation
=> (develop) DIG-1032 DIG-1039 DIG-1041 DIG-1533 DIG-1111 Metrolist-Filter-Pagination-Accessibility-Enhancements

config/default/views.view.events_and_notices.yml, docroot/modules/custom/bos_components/modules/bos_events_and_notices/bos_events_and_notices.module
DIG-5049 Display recurring events in events component.
=> DIG-5049 Display recurring events in events component

docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/metrolist.libraries.yml, docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/update-config.sh
Reverts CityOfBoston/boston.gov-d8#3633 
Revert #2 in sequence
=> Revert "(develop) DIG-1032 DIG-1039 DIG-1041 DIG-1533 DIG-1111 Metrolist-Filter-Pagination-Accessibility-Enhancements"

config/default/views.view.metrolist.yml
=> (develop) Adds extra fields to REST API DIG-1032

config/default/node.type.article.yml, config/default/node.type.department_profile.yml, config/default/node.type.event.yml, config/default/node.type.how_to.yml, config/default/node.type.landing_page.yml, config/default/node.type.listing_page.yml, config/default/node.type.person_profile.yml, config/default/node.type.place_profile.yml, config/default/node.type.post.yml, config/default/node.type.program_initiative_profile.yml, config/default/node.type.topic_page.yml
DIG-5227 Update helper text in Drupal.
=> (develop) Update helper text in Drupal DIG-5227

config/default/views.view.metrolist.yml
DIG-1032 For Kanes filtering tickets (also DIG-5212)
=> (develop) Adds Utilities/Features to metrolist API REST DIG-1032 

composer.json, composer.lock, docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/views/style/MetroListSerializer.php, docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php
DIG-5277 [Drupal Maintenance](https://bostondoit.atlassian.net/browse/DIG-5277)
=> (develop) Drupal Maintenance DIG-5277

config/acquia_prod/xmlsitemap_engines.settings.yml
chore: Match settings in config with those made on the website.
=> (develop) Align config for sitemap submissions
